#!/usr/bin/env swipl
% -*- mode: prolog; coding:utf-8 -*-
:- initialization(main, main).

main(Argv) :-
    ( parse_args(Argv, SourceFiles, Options-[])
    ; format(user_error, 'invalid arguments: ~w~n', [Argv]), fail), !,
    load_terms(SourceFiles, Terms-[]), !,
    writeln('#!/usr/bin/env swipl'),
    writeln('% This code is generated by Micro-GHC compiler'),
    format('% source: ~w~n', [SourceFiles]),
    writeln(':- initialization(main, main).'),
    writeln('% for debug'),
    ( Options = [debug|_]
    -> writeln('dwriteln(X) :- writeln(X).')
    ; writeln('dwriteln(_).') ),
    writeln('% main wrapper'),
    SourceFiles = [FirstSourceFile|_],
    write('main(Args) :- g__main(['), write_term(FirstSourceFile, [quoted(true)]),
    writeln('|Args]).'),
    writeln('% call wrapper'),
    writeln('g__call__(Goal) :- '),
    writeln('    Goal=..[F|Args],atom_concat(\'g__\',F,F2),Goal2=..[F2|Args],'),
    writeln('    call(Goal2).'),
    writeln('g__freeze__(X, G) :- freeze(X, g__call__(G)).'),
    writeln('% compiled codes...'),
    compile(Terms).
parse_args(Argv, SourceFiles, Options-Options2) :-
    phrase(opt_parse_dcg(SourceFiles, Options-Options2), Argv).
opt_parse_dcg([], Options-Options) --> [].
opt_parse_dcg([], Options-Options) -->
    ['-h'], !,
    { format(user_error, 'usage: mlpc_opt <SourceFile..>', []), halt }.
opt_parse_dcg(SourceFiles, [debug|Options]-Options2) -->
    ['-d'], !,
    opt_parse_dcg(SourceFiles, Options-Options2).
opt_parse_dcg([SourceFile | SourceFiles], Options-Options2) -->
    [SourceFile], !,
    opt_parse_dcg(SourceFiles, Options-Options2).
% ----------------------------------------------------------------------
% load source files
% ----------------------------------------------------------------------
load_terms([], Terms-Terms) :- !.
load_terms([SourceFile|SourceFiles], Terms-Terms2) :-
    open(SourceFile, read, Stream, [encoding(utf8)]),
    read_all_terms(Stream, Terms-Terms1),
    close(Stream),
    load_terms(SourceFiles, Terms1-Terms2).
read_all_terms(Stream, Terms-Terms2) :-
    read_term(Stream, Term,
              [variable_names(NameVars),
               singletons(Singletons)]),
    report_singletons(Term, NameVars, Singletons),
    ( Term = end_of_file -> Terms = Terms2
    ; Term = otherwise -> read_all_terms(Stream, Terms-Terms2)
    ; preprocess_term(Term, PreprocessedTerm),
      Terms = [term_data(PreprocessedTerm, NameVars)|Terms1],
      read_all_terms(Stream, Terms1-Terms2) ).
report_singletons(_, _, []) :- !.
report_singletons(Term, Vars,
                  Singletons) :-
    Singletons = [Name=_ | RestSingletons],
    atom_chars(Name, SCs),
    ( SCs = ['_'|_] -> true
    ; term_string(Term, Str, [variable_names(Vars)]),
      format(user_error, 'warning: Singleton ~w in ~s.~n',
             [Name, Str]) ),
    report_singletons(Term, Vars, RestSingletons).
% ----------------------------------------------------------------------
% preprocessing for DCG
% ----------------------------------------------------------------------
preprocess_term((Head --> Guard | Body), (Head2 :- Guard2 | Body2)) :-
    Pred = (Head --> Guard | Body),
    ( may_be_stream(Guard), may_be_stream(Body)
    -> throw(error(invalid_predicate(Pred)))
    ; may_be_stream(Guard)
    -> preprocess_stream(Pred, Guard, In1-In2, Guard2),
       Head =.. [F|Args], append(Args, [In1,In2], Args2),
       Head2 =.. [F|Args2],
       Body2 = Body, !
    ; may_be_stream(Body)
    -> preprocess_stream(Pred, Body, Out1-Out2, Body2),
       Head =.. [F|Args], append(Args, [Out1,Out2], Args2),
       Head2 =.. [F|Args2],
       Guard2 = Guard, ! ).
preprocess_term((Head --> Body), (Head2 :- Body2)) :-
    Pred = (Head --> Body),
    ( may_be_stream(Body)
    -> preprocess_stream(Pred, Body, Out1-Out2, Body2),
       Head =.. [F|Args], append(Args, [Out1,Out2], Args2),
       Head2 =.. [F|Args2], ! ).
preprocess_term(Term, Term) :- !.

may_be_stream(Gs) :- may_be_stream(Gs, false, true).
may_be_stream((G,Gs), Flag, Flag2) :-
    ( (G = {_} ; G = [] ; G = [_|_] ) -> may_be_stream(Gs, true, Flag2)
    ; may_be_stream(Gs, Flag, Flag2) ).
may_be_stream(G, _, true) :- ( G = {_} ; G = [] ; G = [_|_] ), !.
may_be_stream(_, Flag, Flag).

preprocess_stream(Pred, (G,Gs), IO-IO3, (G2,Gs2)) :-
    ( extend_list(G, IO1-IO2)
    -> G2 = (IO = IO1),
       preprocess_stream(Pred, Gs, IO2-IO3, Gs2), !
    ; G = {G0}
    -> G2 = G0,
       preprocess_stream(Pred, Gs, IO-IO3, Gs2), !
    ; G =.. [F|Args], append(Args, [IO,IO1], Args2), G2 =.. [F|Args2],
      preprocess_stream(Pred, Gs, IO1-IO3, Gs2), !
    ; throw(error(invalid_predicate(Pred, G))) ).
preprocess_stream(Pred, G, IO-IO2, G2) :-
    ( extend_list(G, IO1-IO2) -> G2 = (IO = IO1)
    ; G = {G0} -> G2 = G0, IO = IO2
    ; G =.. [F|Args], append(Args, [IO,IO2], Args2), G2 =.. [F|Args2]
    ; throw(error(invalid_predicate(Pred, G))) ).

extend_list([], List-List).
extend_list([V|Values], List-List2) :-
    List = [V|List1], extend_list(Values, List1-List2).
% ----------------------------------------------------------------------
% compiler
% ----------------------------------------------------------------------
compile([]).
compile([term_data(Head :- Guard | Body, NameVars)|Terms]) :-
    !,
    call_guards(Guard, CompiledGuard),
    call_goals(Body, TrustedBody),
    rename_term(Head, Head2),
    write_term((Head2 :- CompiledGuard, !, TrustedBody),
               [variable_names(NameVars), numbervars(true), quoted(true)]),
    writeln('.'),
    compile(Terms).
compile([term_data(Head :- Body, NameVars)|Terms]) :-
    !,
    rename_term(Head, Head2),
    call_goals(Body, TrustedBody),
    write_term((Head2 :- !, TrustedBody),
               [variable_names(NameVars), numbervars(true), quoted(true)]),
    writeln('.'),
    compile(Terms).
compile([term_data(Head, NameVars)|Terms]) :-
    !,
    rename_term(Head, Head2),
    write_term(Head2,
               [variable_names(NameVars), numbervars(true), quoted(true)]),
    writeln('.'),
    compile(Terms).

call_guards((G1, G2), (P1, P2)) :-
    !,
    call_guards(G1, P1),
    call_guards(G2, P2).
call_guards(true, P) :- !, P = true.
call_guards(var(X), P) :- !, P = var(X).
call_guards(nonvar(X), P) :- !, P = nonvar(X).
call_guards(integer(X), P) :- !, P = integer(X).
call_guards(A is B, P) :- !, P = (A is B).
call_guards(A := B, P) :- !, P = (A is B).
call_guards(A = B, P) :- !, P = (A = B).
call_guards(A =\= B, P) :- !, P = (A =\= B).
call_guards(A =:= B, P) :- !, P = (A =:= B).
call_guards(A < B, P) :- !, P = (A < B).
call_guards(A > B, P) :- !, P = (A > B).
call_guards(A =< B, P) :- !, P = (A =< B).
call_guards(A >= B, P) :- !, P = (A >= B).
call_guards(prolog(G), P) :- !, P = G.
call_guards(call(G), P) :- !, P = g__call__(G).
call_guards(freeze(X, G), P) :- !, P = g__freeze__(X, G).
call_guards(G, P) :-
    !,
    rename_term(G, G2), P = G2.

call_goals((P, Q), (P2, !, Q2)) :-
    !,
    call_goals(P, P2),
    call_goals(Q, Q2).
call_goals(true, true).
call_goals(A is B, P) :- !, P = (A is B).
call_goals(A := B, P) :- !, P = (A is B).
call_goals(A = B, P) :- !, P = (A = B).
call_goals(prolog(Q), P) :- !, P = Q.
call_goals(call(G), P) :- !, P = g__call__(G).
call_goals(freeze(X, G), P) :- !, P = g__freeze__(X, G).
call_goals(Q, P) :-
    !, rename_term(Q, Q2), P = Q2.

rename_term(Term, RenamedTerm) :-
    Term =.. [F|Args], atom_concat('g__', F, F2), RenamedTerm =.. [F2|Args].
