#!/usr/bin/env swipl
% This code is generated by MLP compiler
% source: [src/mlpc_opt.mlp,builtin.mlp,src/mlpc_opt_runtime.mlp,src/mlpc_preprocess.mlp]
:- initialization(main, main).
% main wrapper
main(Args) :- g__main(['src/mlpc_opt.mlp'|Args]).
% generated source codes
g__main([_|A]):-g__parse_args(A,B,_-[]),!,g__append_runtime_sources(B,C),!,g__load_term_data(C,D-[]),!,g__preprocess_dcg(D,E),!,g__translate(E,F),!,g__iostream(G),!,g__write_file_header(C,G-H),!,g__write_term_data(F,H).
g__append_runtime_sources([],A):-A=['src/mlpc_opt_runtime.mlp','src/mlpc_preprocess.mlp'].
g__append_runtime_sources([A|B],C):-A='src/mlpc_opt_runtime.mlp',!,g__append_runtime_sources(B,C).
g__append_runtime_sources([A|B],C):-A='src/mlpc_preprocess.mlp',!,g__append_runtime_sources(B,C).
g__append_runtime_sources([A|B],C):-C=[A|D],!,g__append_runtime_sources(B,D).
g__parse_args(A,B,C-D) :- g__phrase(opt_parse_dcg(B,C-D),A,[]).
g__opt_parse_dcg([],A-A,B,C):-B=['-h'|C],!,g__iostream([writeln('usage: mlpc_opt <SourceFile..>'),told]).
g__opt_parse_dcg(A,[debug|B]-C,D,E):-(D=['-d'|F],g__opt_parse_dcg(A,B-C,F,E)),!,true.
g__opt_parse_dcg([A|B],C-D,E,F):-(E=[A|G],g__opt_parse_dcg(B,C-D,G,F)),!,true.
g__opt_parse_dcg([],A-A,B,C) :- B=C,!,true.
g__write_file_header(A,B-C):-A=[D|_],!,B = [ writeln('#!/usr/bin/env swipl'),
  writeln('% This code is generated by MLP compiler'),
  format('% source: ~w~n',[A]),
  writeln(':- initialization(main, main).'),
  writeln('% main wrapper'),
  format('main(Args) :- g__main([\'~s\'|Args]).~n',D),
  writeln('% generated source codes')
| C
].
g__write_term_data([],A) :- A=[told].
g__write_term_data([A|B],C):-A=term_data(D,E),!,C = [ print_term(D,[variable_names(E),numbervars(true),tab_width(4)]),
  writeln('.')
| F
],!,g__write_term_data(B,F).
g__load_term_data([],A-A).
g__load_term_data([A|B],C-D):-g__iostream(E),!,E=[open(A,read,F,[encoding(utf8)])|G],!,g__read_all_terms(G-H,F,C-I),!,H=[close(F),told],!,g__load_term_data(B,I-D).
g__read_all_terms(A-B,C,D-E):-A = [ read_term(C,F,[variable_names(G),singletons(H),syntax_errors(dec10)])
| I
],!,g__report_singletons(F,G,H,I-J),!,g__read_all_terms_aux(F,G,J-B,C,D-E).
g__read_all_terms_aux(A,_,B-C,_,D-E) :- A=end_of_file,!,B=C,!,D=E.
g__read_all_terms_aux(A,_,B-C,D,E-F):-A=otherwise,!,g__read_all_terms(B-C,D,E-F).
g__read_all_terms_aux(A,B,C-D,E,F-G):-g__preprocess_dcg_term(A,H),!,F=[term_data(H,B)|I],!,g__read_all_terms(C-D,E,I-G).
g__report_singletons(_,_,[],A-A).
g__report_singletons(A,B,C,D-E):-C=[F=_|G],!,g__atom_chars(F,H),!,g__report_singletons_aux(H,F,A,B,G,D-E).
g__report_singletons_aux(A,_,B,C,D,E-F):-A=['_'|_],!,g__report_singletons(B,C,D,E-F).
g__report_singletons_aux(_,A,B,C,D,E-F):-g__term_string(B,G,[variable_names(C)]),!,E=[format(user_error,'warning: Singleton ~w in ~s.~n',[A,G])|H],!,g__report_singletons(B,C,D,H-F).
'g__:='(A,B) :- A is B.
g__term_to_atom(A,B) :- term_to_atom(A,B),!,true.
g__atom_chars(A,B) :- atom_chars(A,B),!,true.
g__atom_concat(A,B,C) :- atom_concat(A,B,C),!,true.
g__atom_number(A,B) :- atom_number(A,B),!,true.
g__term_string(A,B,C) :- term_string(A,B,C),!,true.
g__functor(A,B,C) :- functor(A,B,C),!,true.
g__phrase(A,B,C):-A=..[D|E],!,g__append(E,[B,C],F),!,G=..[D|F],!,g__m__call__(G).
g__append(A,B,C) :- append(A,B,C),!,true.
g__debug(A) :- debug(A),!,true.
g__nodebug(A) :- nodebug(A),!,true.
g__debug(A,B,C) :- debug(A,B,C),!,true.
g__write(A) :- write(A),!,true.
g__writeln(A) :- writeln(A),!,true.
g__nl :- nl,!,true.
g__write(A,B) :- write(A,B),!,true.
g__writeln(A,B) :- writeln(A,B),!,true.
g__nl(A) :- nl(A),!,true.
g__iostream(A) :- A=[_|_],!,g__iostream_loop(A).
g__iostream_loop(A) :- var(A),!,g__m__freeze__(A,iostream_loop(A)).
g__iostream_loop([A|B]):-var(A),!,g__m__freeze__(A,iostream_loop([A|B])).
g__iostream_loop([]).
g__iostream_loop([told]).
g__iostream_loop([write(A)|B]) :- write(A),!,g__iostream_loop(B).
g__iostream_loop([writeln(A)|B]) :- writeln(A),!,g__iostream_loop(B).
g__iostream_loop([write_term(A,B)|C]):-write_term(A,B),!,g__iostream_loop(C).
g__iostream_loop([print_term(A,B)|C]):-print_term(A,B),!,g__iostream_loop(C).
g__iostream_loop([format(A,B,C)|D]):-format(A,B,C),!,g__iostream_loop(D).
g__iostream_loop([format(A,B)|C]) :- format(A,B),!,g__iostream_loop(C).
g__iostream_loop([nl|A]) :- nl,!,g__iostream_loop(A).
g__iostream_loop([ttyflush|A]) :- ttyflush,!,g__iostream_loop(A).
g__iostream_loop([flush(A)|B]):-ttyflush,!,A=flushed,!,g__iostream_loop(B).
g__iostream_loop([read(A)|B]) :- read(A),!,g__iostream_loop(B).
g__iostream_loop([open(A,B,C,D)|E]):-open(A,B,C,D),!,g__iostream_loop(E).
g__iostream_loop([close(A)|B]) :- close(A),!,g__iostream_loop(B).
g__iostream_loop([prompt1(A)|B]) :- prompt1(A),!,g__iostream_loop(B).
g__iostream_loop([read_term(A,B,C)|D]):-read_term(A,B,C),!,g__iostream_loop(D).
g__iostream_loop([A|B]):-format(user_error,'error: unknown iostream operation: ~w~n',[A]),!,g__iostream_loop(B).
g__translate([],[]).
g__translate([term_data((A:-B|C),D)|E],[term_data((F:-G,!,H),D)|I]):-g__call_guards(B,G),!,g__call_goals(C,H),!,g__rename_term(A,F),!,g__translate(E,I).
g__translate([term_data((A:-B),C)|D],[term_data((E:-F),C)|G]):-g__rename_term(A,E),!,g__call_goals(B,F),!,g__translate(D,G).
g__translate([term_data(A,B)|C],[term_data(D,B)|E]):-g__rename_term(A,D),!,g__translate(C,E).
g__call_guards((A,B),(C,D)) :- g__call_guards(A,C),!,g__call_guards(B,D).
g__call_guards(true,A) :- A=true.
g__call_guards(var(A),B) :- B=var(A).
g__call_guards(nonvar(A),B) :- B=nonvar(A).
g__call_guards(integer(A),B) :- B=integer(A).
g__call_guards(A is B,C) :- C=(A is B).
g__call_guards(A:=B,C) :- C=(A is B).
g__call_guards(A=B,C) :- C=(A=B).
g__call_guards(A=\=B,C) :- C=(A=\=B).
g__call_guards(A=:=B,C) :- C=(A=:=B).
g__call_guards(A<B,C) :- C=(A<B).
g__call_guards(A>B,C) :- C=(A>B).
g__call_guards(A=<B,C) :- C=(A=<B).
g__call_guards(A>=B,C) :- C=(A>=B).
g__call_guards(A=..B,C) :- C=(A=..B).
g__call_guards(prolog(A),B) :- B=A.
g__call_guards(call(A),B) :- B=g__m__call__(A).
g__call_guards(freeze(A,B),C) :- C=g__m__freeze__(A,B).
g__call_guards(catch(A,B,C),D) :- D=g__m__catch__(A,B,C).
g__call_guards(abolish(A,B),C) :- C=g__m__abolish__(A,B).
g__call_guards(asserta(A),B) :- B=g__m__asserta__(A).
g__call_guards(assertz(A),B) :- B=g__m__assertz__(A).
g__call_guards(A,B) :- g__rename_term(A,C),!,B=C.
g__call_goals((A,B),(C,!,D)) :- g__call_goals(A,C),!,g__call_goals(B,D).
g__call_goals(true,true).
g__call_goals(A is B,C) :- C=(A is B).
g__call_goals(A:=B,C) :- C=(A is B).
g__call_goals(A=B,C) :- C=(A=B).
g__call_goals(A=..B,C) :- C=(A=..B).
g__call_goals(prolog(A),B) :- B=A.
g__call_goals(call(A),B) :- B=g__m__call__(A).
g__call_goals(freeze(A,B),C) :- C=g__m__freeze__(A,B).
g__call_goals(catch(A,B,C),D) :- D=g__m__catch__(A,B,C).
g__call_goals(abolish(A,B),C) :- C=g__m__abolish__(A,B).
g__call_goals(asserta(A),B) :- B=g__m__asserta__(A).
g__call_goals(assertz(A),B) :- B=g__m__assertz__(A).
g__call_goals(A,B) :- g__rename_term(A,C),!,B=C.
g__rename_term(A,B) :- A=..[C|D],!,g__atom_concat(g__,C,E),!,B=..[E|D].
g__m__rename__(A,B) :- atom_concat(g__,A,B).
g__m__rename_term__(A,B) :- A=..[C|D],!,g__m__rename__(C,E),!,B=..[E|D].
g__m__call__(A) :- g__m__rename_term__(A,B),!,call(B).
g__m__freeze__(A,B) :- g__m__rename_term__(B,C),!,freeze(A,C).
g__m__catch__(A,B,C):-g__m__rename_term__(A,D),!,g__m__rename_term__(C,E),!,catch(D,B,E).
g__m__abolish__(A,B) :- g__m__rename__(A,C),!,abolish(C,B).
g__m__asserta__(A):-g__translate([term_data(A,[])],[term_data(B,_)]),!,asserta(B).
g__m__assertz__(A):-g__translate([term_data(A,[])],[term_data(B,_)]),!,assertz(B).
g__preprocess_dcg([],[]).
g__preprocess_dcg([term_data(A,B)|C],[term_data(D,B)|E]):-g__preprocess_dcg_term(A,D),!,g__preprocess_dcg(C,E).
g__preprocess_dcg_term((A-->B|C),_):-(D=(A-->B'|'C),g__may_be_stream(B),g__may_be_stream(C)),!,g__throw(error(invalid_predicate(D))).
g__preprocess_dcg_term((A-->B|C),(D:-E|F)):-(G=(A-->B'|'C),g__may_be_stream(B)),!,g__preprocess_dcg_stream(G,B,H-I,E),!,A=..[J|K],!,g__append(K,[H,I],L),!,D=..[J|L],!,F=C.
g__preprocess_dcg_term((A-->B|C),(D:-E|F)):-(G=(A-->B'|'C),g__may_be_stream(C)),!,g__preprocess_dcg_stream(G,C,H-I,F),!,A=..[J|K],!,g__append(K,[H,I],L),!,D=..[J|L],!,E=B.
g__preprocess_dcg_term((A-->B),(C:-D)):-(E=(A-->B),g__may_be_stream(B)),!,g__preprocess_dcg_stream(E,B,F-G,D),!,A=..[H|I],!,g__append(I,[F,G],J),!,C=..[H|J].
g__preprocess_dcg_term(A,A).
g__may_be_stream(A) :- (g__may_be_stream(A,false,B),B=true),!,true.
g__may_be_stream(({_},_),_,A) :- A=true.
g__may_be_stream(([],_),_,A) :- A=true.
g__may_be_stream(([_|_],_),_,A) :- A=true.
g__may_be_stream((_,A),B,C) :- g__may_be_stream(A,B,C).
g__may_be_stream({_},_,A) :- A=true.
g__may_be_stream([],_,A) :- A=true.
g__may_be_stream([_|_],_,A) :- A=true.
g__may_be_stream(_,A,B) :- B=A.
g__preprocess_dcg_stream(A,(B,C),D-E,F):-B=[],!,g__preprocess_dcg_stream(A,C,D-E,F).
g__preprocess_dcg_stream(A,(B,C),D-E,(F,G)):-B=[_|_],!,g__extend_list(B,H-I),!,F=(D=H),!,g__preprocess_dcg_stream(A,C,I-E,G).
g__preprocess_dcg_stream(A,(B,C),D-E,(F,G)):-B={H},!,F=H,!,g__preprocess_dcg_stream(A,C,D-E,G).
g__preprocess_dcg_stream(A,(B,C),D-E,(F,G)):-B=..[H|I],!,g__append(I,[D,J],K),!,F=..[H|K],!,g__preprocess_dcg_stream(A,C,J-E,G).
g__preprocess_dcg_stream(_,A,B-C,D) :- A=[],!,D=(B=C).
g__preprocess_dcg_stream(_,A,B-C,D):-A=[_|_],!,g__extend_list(A,E-C),!,D=(B=E).
g__preprocess_dcg_stream(_,A,B-C,D) :- A={E},!,D=E,!,B=C.
g__preprocess_dcg_stream(_,A,B-C,D):-A=..[E|F],!,g__append(F,[B,C],G),!,D=..[E|G].
g__preprocess_dcg_stream(A,(B,_),_,_):-g__throw(error(invalid_predicate(A,B))).
g__preprocess_dcg_stream(A,B,_,_):-g__throw(error(invalid_predicate(A,B))).
g__extend_list([],A-A).
g__extend_list([A|B],C-D) :- C=[A|E],!,g__extend_list(B,E-D).
