#!/usr/bin/env swipl
% This code is generated by MLP compiler
% source: [src/mlpc_opt.mlp,builtin.mlp,src/mlpc_opt_runtime.mlp]
:- initialization(main, main).
% main wrapper
main(Args) :- g__main(['src/mlpc_opt.mlp'|Args]).
% generated source codes
g__main([_132|Argv]):-g__parse_args(Argv,SourceFiles,_142-[]),!,g__append_runtime_source(SourceFiles,SourceFiles2),!,g__load_term_data(SourceFiles2,TermData-[]),!,g__preprocess(TermData,PTermData),!,g__translate(PTermData,PrologTermData),!,g__iostream(IO),!,g__write_file_header(SourceFiles2,IO-IO1),!,g__write_term_data(PrologTermData,IO1).
g__append_runtime_source([],SourceFiles2):-SourceFiles2=['src/mlpc_opt_runtime.mlp'].
g__append_runtime_source([SourceFile|SourceFiles],SourceFiles2):-SourceFile='src/mlpc_opt_runtime.mlp',!,g__append_runtime_source(SourceFiles,SourceFiles2).
g__append_runtime_source([SourceFile|SourceFiles],SourceFiles2):-SourceFiles2=[SourceFile|SourceFiles1],!,g__append_runtime_source(SourceFiles,SourceFiles1).
g__parse_args(Argv,SourceFiles,Options-Options2):-g__phrase(opt_parse_dcg(SourceFiles,Options-Options2),Argv,[]).
g__opt_parse_dcg([],Options-Options,_696,_698):-_696=['-h'|_698],!,g__iostream([writeln('usage: mlpc_opt <SourceFile..>'),told]).
g__opt_parse_dcg(SourceFiles,[debug|Options]-Options2,_792,_794):-(_792=['-d'|_802],g__opt_parse_dcg(SourceFiles,Options-Options2,_802,_794)),!,true.
g__opt_parse_dcg([SourceFile|SourceFiles],Options-Options2,_914,_916):-(_914=[SourceFile|_924],g__opt_parse_dcg(SourceFiles,Options-Options2,_924,_916)),!,true.
g__opt_parse_dcg([],Options-Options,_988,_990):-_988=_990,!,true.
g__write_file_header(SourceFiles,IO-IO1):-SourceFiles=[FirstSourceFile|_1026],!,IO=[writeln('#!/usr/bin/env swipl'),writeln('% This code is generated by MLP compiler'),format('% source: ~w~n',[SourceFiles]),writeln(':- initialization(main, main).'),writeln('% main wrapper'),format('main(Args) :- g__main([\'~s\'|Args]).~n',FirstSourceFile),writeln('% generated source codes')|IO1].
g__write_term_data([],IO):-IO=[told].
g__write_term_data([TD|Terms],IO):-TD=term_data(Term,NameVars),!,IO=[write_term(Term,[variable_names(NameVars),numbervars(true),quoted(true)]),writeln('.')|IO2],!,g__write_term_data(Terms,IO2).
g__load_term_data([],Terms-Terms).
g__load_term_data([SourceFile|SourceFiles],Terms-Terms2):-g__iostream(IO),!,IO=[open(SourceFile,read,Stream,[encoding(utf8)])|IO1],!,g__read_all_terms(IO1-IO2,Stream,Terms-Terms1),!,IO2=[close(Stream),told],!,g__load_term_data(SourceFiles,Terms1-Terms2).
g__read_all_terms(IO-IO3,Stream,Terms-Terms2):-IO=[read_term(Stream,Term,[variable_names(NameVars),singletons(Singletons),syntax_errors(dec10)])|IO1],!,g__report_singletons(Term,NameVars,Singletons,IO1-IO2),!,g__read_all_terms_aux(Term,NameVars,IO2-IO3,Stream,Terms-Terms2).
g__read_all_terms_aux(Term,_1952,IO-IO2,_1956,Terms-Terms2):-Term=end_of_file,!,IO=IO2,!,Terms=Terms2.
g__read_all_terms_aux(Term,_2072,IO-IO2,Stream,Terms-Terms2):-Term=otherwise,!,g__read_all_terms(IO-IO2,Stream,Terms-Terms2).
g__read_all_terms_aux(Term,NameVars,IO-IO2,Stream,Terms-Terms2):-g__preprocess_term(Term,PreprocessedTerm),!,Terms=[term_data(PreprocessedTerm,NameVars)|Terms1],!,g__read_all_terms(IO-IO2,Stream,Terms1-Terms2).
g__report_singletons(_2394,_2396,[],IO-IO).
g__report_singletons(Term,Vars,Singletons,IO-IO2):-Singletons=[Name=_2442|RestSingletons],!,g__atom_chars(Name,SCs),!,g__report_singletons_aux(SCs,Name,Term,Vars,RestSingletons,IO-IO2).
g__report_singletons_aux(SCs,_2612,Term,Vars,RestSingletons,IO-IO2):-SCs=['_'|_2628],!,g__report_singletons(Term,Vars,RestSingletons,IO-IO2).
g__report_singletons_aux(_2756,Name,Term,Vars,RestSingletons,IO-IO2):-g__term_string(Term,Str,[variable_names(Vars)]),!,IO=[format(user_error,'warning: Singleton ~w in ~s.~n',[Name,Str])|IO1],!,g__report_singletons(Term,Vars,RestSingletons,IO1-IO2).
'g__:='(A,B):-A is B.
g__term_to_atom(T,A):-term_to_atom(T,A),!,true.
g__atom_chars(A,Cs):-atom_chars(A,Cs),!,true.
g__atom_concat(A,B,C):-atom_concat(A,B,C),!,true.
g__atom_number(A,N):-atom_number(A,N),!,true.
g__term_string(T,S,Opts):-term_string(T,S,Opts),!,true.
g__functor(Func,Name,Arity):-functor(Func,Name,Arity),!,true.
g__phrase(P,A,B):-P=..[F|Args],!,g__append(Args,[A,B],Args2),!,P2=..[F|Args2],!,g__m__call__(P2).
g__append(A,B,C):-append(A,B,C),!,true.
g__debug(Topic):-debug(Topic),!,true.
g__debug(Topic,Format,Args):-debug(Topic,Format,Args),!,true.
g__write(X):-write(X),!,true.
g__writeln(X):-writeln(X),!,true.
g__nl:-nl,!,true.
g__write(Stream,X):-write(Stream,X),!,true.
g__writeln(Stream,X):-writeln(Stream,X),!,true.
g__nl(Stream):-nl(Stream),!,true.
g__iostream(IO):-IO=[_4064|_4066],!,g__iostream_loop(IO).
g__iostream_loop(Cmds):-var(Cmds),!,g__m__freeze__(Cmds,iostream_loop(Cmds)).
g__iostream_loop([Cmd|Cmds]):-var(Cmd),!,g__m__freeze__(Cmd,iostream_loop([Cmd|Cmds])).
g__iostream_loop([]).
g__iostream_loop([told]).
g__iostream_loop([write(P)|Cmds]):-write(P),!,g__iostream_loop(Cmds).
g__iostream_loop([writeln(P)|Cmds]):-writeln(P),!,g__iostream_loop(Cmds).
g__iostream_loop([write_term(T,Opts)|Cmds]):-write_term(T,Opts),!,g__iostream_loop(Cmds).
g__iostream_loop([print_term(T,Opts)|Cmds]):-print_term(T,Opts),!,g__iostream_loop(Cmds).
g__iostream_loop([format(Stream,Message,Args)|Cmds]):-format(Stream,Message,Args),!,g__iostream_loop(Cmds).
g__iostream_loop([format(Message,Args)|Cmds]):-format(Message,Args),!,g__iostream_loop(Cmds).
g__iostream_loop([nl|Cmds]):-nl,!,g__iostream_loop(Cmds).
g__iostream_loop([ttyflush|Cmds]):-ttyflush,!,g__iostream_loop(Cmds).
g__iostream_loop([flush(X)|Cmds]):-ttyflush,!,X=flushed,!,g__iostream_loop(Cmds).
g__iostream_loop([read(P)|Cmds]):-read(P),!,g__iostream_loop(Cmds).
g__iostream_loop([open(File,Mode,Stream,Opts)|Cmds]):-open(File,Mode,Stream,Opts),!,g__iostream_loop(Cmds).
g__iostream_loop([close(Stream)|Cmds]):-close(Stream),!,g__iostream_loop(Cmds).
g__iostream_loop([prompt1(Prompt)|Cmds]):-prompt1(Prompt),!,g__iostream_loop(Cmds).
g__iostream_loop([read_term(From,Term,Opts)|Cmds]):-read_term(From,Term,Opts),!,g__iostream_loop(Cmds).
g__iostream_loop([Op|Cmds]):-format(user_error,'error: unknown iostream operation: ~w~n',[Op]),!,g__iostream_loop(Cmds).
g__preprocess([],[]).
g__preprocess([term_data(Term,NameVars)|Terms],[term_data(PreProcessedTerm,NameVars)|Terms2]):-g__preprocess_term(Term,PreProcessedTerm),!,g__preprocess(Terms,Terms2).
g__preprocess_term((Head-->Guard|Body),_5624):-(Pred=(Head-->Guard|Body),g__may_be_stream(Guard),g__may_be_stream(Body)),!,g__throw(error(invalid_predicate(Pred))).
g__preprocess_term((Head-->Guard|Body),(Head2:-Guard2|Body2)):-(Pred=(Head-->Guard|Body),g__may_be_stream(Guard)),!,g__preprocess_stream(Pred,Guard,In1-In2,Guard2),!,Head=..[F|Args],!,g__append(Args,[In1,In2],Args2),!,Head2=..[F|Args2],!,Body2=Body.
g__preprocess_term((Head-->Guard|Body),(Head2:-Guard2|Body2)):-(Pred=(Head-->Guard|Body),g__may_be_stream(Body)),!,g__preprocess_stream(Pred,Body,Out1-Out2,Body2),!,Head=..[F|Args],!,g__append(Args,[Out1,Out2],Args2),!,Head2=..[F|Args2],!,Guard2=Guard.
g__preprocess_term((Head-->Body),(Head2:-Body2)):-(Pred=(Head-->Body),g__may_be_stream(Body)),!,g__preprocess_stream(Pred,Body,Out1-Out2,Body2),!,Head=..[F|Args],!,g__append(Args,[Out1,Out2],Args2),!,Head2=..[F|Args2].
g__preprocess_term(Term,Term).
g__may_be_stream(Gs):-(g__may_be_stream(Gs,false,Result),Result=true),!,true.
g__may_be_stream(({_6734},_6740),_6746,Flag2):-Flag2=true.
g__may_be_stream(([],_6784),_6790,Flag2):-Flag2=true.
g__may_be_stream(([_6828|_6830],_6836),_6842,Flag2):-Flag2=true.
g__may_be_stream((_6878,Gs),Flag,Flag2):-g__may_be_stream(Gs,Flag,Flag2).
g__may_be_stream({_6948},_6954,Flag2):-Flag2=true.
g__may_be_stream([],_6992,Flag2):-Flag2=true.
g__may_be_stream([_7030|_7032],_7038,Flag2):-Flag2=true.
g__may_be_stream(_7080,Flag,Flag2):-Flag2=Flag.
g__preprocess_stream(Pred,(G,Gs),IO-IO2,Gs2):-G=[],!,g__preprocess_stream(Pred,Gs,IO-IO2,Gs2).
g__preprocess_stream(Pred,(G,Gs),IO-IO3,(G2,Gs2)):-G=[_7294|_7296],!,g__extend_list(G,IO1-IO2),!,G2=(IO=IO1),!,g__preprocess_stream(Pred,Gs,IO2-IO3,Gs2).
g__preprocess_stream(Pred,(G,Gs),IO-IO2,(G2,Gs2)):-G={G0},!,G2=G0,!,g__preprocess_stream(Pred,Gs,IO-IO2,Gs2).
g__preprocess_stream(Pred,(G,Gs),IO-IO2,(G2,Gs2)):-G=..[F|Args],!,g__append(Args,[IO,IO1],Args2),!,G2=..[F|Args2],!,g__preprocess_stream(Pred,Gs,IO1-IO2,Gs2).
g__preprocess_stream(_7926,G,IO-IO2,G2):-G=[],!,G2=(IO=IO2).
g__preprocess_stream(_8026,G,IO-IO2,G2):-G=[_8038|_8040],!,g__extend_list(G,IO1-IO2),!,G2=(IO=IO1).
g__preprocess_stream(_8164,G,IO-IO2,G2):-G={G0},!,G2=G0,!,IO=IO2.
g__preprocess_stream(_8286,G,IO-IO2,G2):-G=..[F|Args],!,g__append(Args,[IO,IO2],Args2),!,G2=..[F|Args2].
g__preprocess_stream(Pred,(G,_8456),_8464,_8466):-g__throw(error(invalid_predicate(Pred,G))).
g__preprocess_stream(Pred,G,_8524,_8526):-g__throw(error(invalid_predicate(Pred,G))).
g__extend_list([],List-List).
g__extend_list([V|Values],List-List2):-List=[V|List1],!,g__extend_list(Values,List1-List2).
g__translate([],[]).
g__translate([term_data((Head:-Guard|Body),NameVars)|Terms],[term_data((Head2:-CompiledGuard,!,TrustedBody),NameVars)|Terms2]):-g__call_guards(Guard,CompiledGuard),!,g__call_goals(Body,TrustedBody),!,g__rename_term(Head,Head2),!,g__translate(Terms,Terms2).
g__translate([term_data((Head:-Body),NameVars)|Terms],[term_data((Head2:-TrustedBody),NameVars)|Terms2]):-g__rename_term(Head,Head2),!,g__call_goals(Body,TrustedBody),!,g__translate(Terms,Terms2).
g__translate([term_data(Head,NameVars)|Terms],[term_data(Head2,NameVars)|Terms2]):-g__rename_term(Head,Head2),!,g__translate(Terms,Terms2).
g__call_guards((G1,G2),(P1,P2)):-g__call_guards(G1,P1),!,g__call_guards(G2,P2).
g__call_guards(true,P):-P=true.
g__call_guards(var(X),P):-P=var(X).
g__call_guards(nonvar(X),P):-P=nonvar(X).
g__call_guards(integer(X),P):-P=integer(X).
g__call_guards(A is B,P):-P=(A is B).
g__call_guards(A:=B,P):-P=(A is B).
g__call_guards(A=B,P):-P=(A=B).
g__call_guards(A=\=B,P):-P=(A=\=B).
g__call_guards(A=:=B,P):-P=(A=:=B).
g__call_guards(A<B,P):-P=(A<B).
g__call_guards(A>B,P):-P=(A>B).
g__call_guards(A=<B,P):-P=(A=<B).
g__call_guards(A>=B,P):-P=(A>=B).
g__call_guards(F=..L,P):-P=(F=..L).
g__call_guards(prolog(G),P):-P=G.
g__call_guards(call(G),P):-P=g__m__call__(G).
g__call_guards(freeze(X,G),P):-P=g__m__freeze__(X,G).
g__call_guards(catch(G,Error,Recover),P):-P=g__m__catch__(G,Error,Recover).
g__call_guards(abolish(Func,Arity),P):-P=g__m__abolish__(Func,Arity).
g__call_guards(asserta(Term),P):-P=g__m__asserta__(Term).
g__call_guards(assertz(Term),P):-P=g__m__assertz__(Term).
g__call_guards(G,P):-g__rename_term(G,G2),!,P=G2.
g__call_goals((P,Q),(P2,!,Q2)):-g__call_goals(P,P2),!,g__call_goals(Q,Q2).
g__call_goals(true,true).
g__call_goals(A is B,P):-P=(A is B).
g__call_goals(A:=B,P):-P=(A is B).
g__call_goals(A=B,P):-P=(A=B).
g__call_goals(F=..L,P):-P=(F=..L).
g__call_goals(prolog(Q),P):-P=Q.
g__call_goals(call(G),P):-P=g__m__call__(G).
g__call_goals(freeze(X,G),P):-P=g__m__freeze__(X,G).
g__call_goals(catch(G,Error,Recover),P):-P=g__m__catch__(G,Error,Recover).
g__call_goals(abolish(Func,Arity),P):-P=g__m__abolish__(Func,Arity).
g__call_goals(asserta(Term),P):-P=g__m__asserta__(Term).
g__call_goals(assertz(Term),P):-P=g__m__assertz__(Term).
g__call_goals(Q,P):-g__rename_term(Q,Q2),!,P=Q2.
g__rename_term(Term,RenamedTerm):-Term=..[F|Args],!,g__atom_concat(g__,F,F2),!,RenamedTerm=..[F2|Args].
g__m__rename__(Name,Name2):-atom_concat(g__,Name,Name2).
g__m__rename_term__(Term,Term2):-Term=..[F|Args],!,g__m__rename__(F,F2),!,Term2=..[F2|Args].
g__m__call__(G):-g__m__rename_term__(G,G2),!,call(G2).
g__m__freeze__(X,G):-g__m__rename_term__(G,G2),!,freeze(X,G2).
g__m__catch__(G,Error,Recover):-g__m__rename_term__(G,G2),!,g__m__rename_term__(Recover,Recover2),!,catch(G2,Error,Recover2).
g__m__abolish__(Name,Arity):-g__m__rename__(Name,Name2),!,abolish(Name2,Arity).
g__m__asserta__(Term):-g__translate([term_data(Term,[])],[term_data(Term2,_12460)]),!,asserta(Term2).
g__m__assertz__(Term):-g__translate([term_data(Term,[])],[term_data(Term2,_12560)]),!,assertz(Term2).
