#!/usr/bin/env swipl
% This code is generated by MLP compiler
% source: [src/mlpc.mlp,builtin.mlp,src/mlpc_runtime.mlp,src/mlpc_preprocess.mlp]
:- use_module(library(chr)).
:- initialization('$__main', main).
% main wrapper
'$__main' :-
    current_prolog_flag(argv, Argv),
    main(['src/mlpc.mlp'|Argv]).
% runtime predicates
% call wrapper
'$__guard__'(Position, Head, RealGoal) :- 
    functor(Head, Name, Arity),
    ( call(RealGoal)
    -> debug(mlpc, '[runtime] ~w: ~p',
             [Position,
              success(Name/Arity, guard, RealGoal)])
    ; debug(mlpc, '[runtime] ~w: ~p',
            [Position,
             fail(Name/Arity, guard, RealGoal)]), !, fail ).
'$__guard__'(Position, Head, DispGoal, RealGoal) :- 
    functor(Head, Name, Arity),
    ( call(RealGoal)
    -> debug(mlpc, '[runtime] ~w: ~p',
             [Position,
              success(Name/Arity, guard, DispGoal)])
    ; debug(mlpc, '[runtime] ~w: ~p',
            [Position,
             fail(Name/Arity, guard, RealGoal)]), !, fail ).
'$__body__'(Position, Head, RealGoal) :-
    functor(Head, Name, Arity),
    ( call(RealGoal)
    -> debug(mlpc, '[runtime] ~w: ~p',
             [Position,
              success(Name/Arity, body, RealGoal)])
    ; throw(error(mlp_error(body_failed(RealGoal)),
            context(Name / Arity, source(Position)))) ).
'$__body__'(Position, Head, DispGoal, RealGoal) :-
    functor(Head, Name, Arity),
    ( call(RealGoal)
    -> debug(mlpc, '[runtime] ~w: ~p',
             [Position,
              success(Name/Arity, body, DispGoal)])
    ; throw(error(mlp_error(body_failed(DispGoal)),
            context(Name / Arity, source(Position)))) ).
% generated source codes
:- use_module(library(chr)).
main([A|B]):-!,'$__body__'('src/mlpc.mlp':4,
			main([A|B]),
			debug(main,'~p: ~p',[main/1,parse_args])),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),parse_args(B,C,D-[])),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),append_runtime_sources(C,E)),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),load_term_data(E,F-[])),!,'$__body__'('src/mlpc.mlp':4,
			main([A|B]),
			debug(main,'~p: ~p',[main/1,translate])),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),'$__translate__'(F,G)),!,'$__body__'('src/mlpc.mlp':4,
			main([A|B]),
			debug(main,'~p: ~p',[main/1,write_file_header])),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),iostream(H)),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),write_file_header(E,D,H-I)),!,'$__body__'('src/mlpc.mlp':4,
			main([A|B]),
			debug(main,'~p: ~p',[main/1,write_term_data(G)])),!,'$__body__'('src/mlpc.mlp':4,main([A|B]),write_term_data(G,I)),!,'$__body__'('src/mlpc.mlp':4,
			main([A|B]),
			debug(main,'~p: ~p',[main/1,done])).
append_runtime_sources([],A):-!,'$__body__'('src/mlpc.mlp':20,
			append_runtime_sources([],A),
			A=['src/mlpc_runtime.mlp','src/mlpc_preprocess.mlp']).
append_runtime_sources([A|B],C):-'$__guard__'('src/mlpc.mlp':23,
			 append_runtime_sources([A|B],C),
			 A='src/mlpc_runtime.mlp'),!,'$__body__'('src/mlpc.mlp':23,
			append_runtime_sources([A|B],C),
			append_runtime_sources(B,C)).
append_runtime_sources([A|B],C):-'$__guard__'('src/mlpc.mlp':26,
			 append_runtime_sources([A|B],C),
			 A='src/mlpc_preprocess.mlp'),!,'$__body__'('src/mlpc.mlp':26,
			append_runtime_sources([A|B],C),
			append_runtime_sources(B,C)).
append_runtime_sources([A|B],C):-!,'$__body__'('src/mlpc.mlp':30,append_runtime_sources([A|B],C),C=[A|D]),!,'$__body__'('src/mlpc.mlp':30,
			append_runtime_sources([A|B],C),
			append_runtime_sources(B,D)).
parse_args(A,B,C-D):-!,'$__body__'('src/mlpc.mlp':33,
			parse_args(A,B,C-D),
			phrase(opt_parse_dcg(B,C-D),A,[])).
opt_parse_dcg([],A-A,B,C):-'$__guard__'('src/mlpc.mlp':36,opt_parse_dcg([],A-A,B,C),B=['-h'|C]),!,'$__body__'('src/mlpc.mlp':36,
			opt_parse_dcg([],A-A,B,C),
			iostream([writeln('usage: mlpc_opt <SourceFile..>'),told])).
opt_parse_dcg(A,[debug|B]-C,D,E):-( '$__guard__'('src/mlpc.mlp':39,
			   opt_parse_dcg(A,[debug|B]-C,D,E),
			   D=['-d'|F]),
  '$__guard__'('src/mlpc.mlp':39,
			   opt_parse_dcg(A,[debug|B]-C,D,E),
			   opt_parse_dcg(A,B-C,F,E))
),!,'$__body__'('src/mlpc.mlp':39,
			opt_parse_dcg(A,[debug|B]-C,D,E),
			debug(main)),!,'$__body__'('src/mlpc.mlp':39,
			opt_parse_dcg(A,[debug|B]-C,D,E),
			debug(preprocess)),!,'$__body__'('src/mlpc.mlp':39,
			opt_parse_dcg(A,[debug|B]-C,D,E),
			debug(translate)),!,'$__body__'('src/mlpc.mlp':39,
			opt_parse_dcg(A,[debug|B]-C,D,E),
			debug(mlpc)).
opt_parse_dcg(A,B-C,D,E):-( '$__guard__'('src/mlpc.mlp':43,
			   opt_parse_dcg(A,B-C,D,E),
			   D=['-d_main'|F]),
  '$__guard__'('src/mlpc.mlp':43,
			   opt_parse_dcg(A,B-C,D,E),
			   opt_parse_dcg(A,B-C,F,E))
),!,'$__body__'('src/mlpc.mlp':43,opt_parse_dcg(A,B-C,D,E),debug(main)).
opt_parse_dcg(A,B-C,D,E):-( '$__guard__'('src/mlpc.mlp':47,
			   opt_parse_dcg(A,B-C,D,E),
			   D=['-d_preprocess'|F]),
  '$__guard__'('src/mlpc.mlp':47,
			   opt_parse_dcg(A,B-C,D,E),
			   opt_parse_dcg(A,B-C,F,E))
),!,'$__body__'('src/mlpc.mlp':47,
			opt_parse_dcg(A,B-C,D,E),
			debug(preprocess)).
opt_parse_dcg(A,B-C,D,E):-( '$__guard__'('src/mlpc.mlp':51,
			   opt_parse_dcg(A,B-C,D,E),
			   D=['-d_translate'|F]),
  '$__guard__'('src/mlpc.mlp':51,
			   opt_parse_dcg(A,B-C,D,E),
			   opt_parse_dcg(A,B-C,F,E))
),!,'$__body__'('src/mlpc.mlp':51,
			opt_parse_dcg(A,B-C,D,E),
			debug(translate)).
opt_parse_dcg(A,B-C,D,E):-( '$__guard__'('src/mlpc.mlp':55,
			   opt_parse_dcg(A,B-C,D,E),
			   D=['-d_mlpc'|F]),
  '$__guard__'('src/mlpc.mlp':55,
			   opt_parse_dcg(A,B-C,D,E),
			   opt_parse_dcg(A,B-C,F,E))
),!,'$__body__'('src/mlpc.mlp':55,opt_parse_dcg(A,B-C,D,E),debug(mlpc)).
opt_parse_dcg([A|B],C-D,E,F):-( '$__guard__'('src/mlpc.mlp':59,opt_parse_dcg([A|B],C-D,E,F),E=[A|G]),
  '$__guard__'('src/mlpc.mlp':59,
			   opt_parse_dcg([A|B],C-D,E,F),
			   opt_parse_dcg(B,C-D,G,F))
),!,true.
opt_parse_dcg([],A-A,B,C):-'$__guard__'('src/mlpc.mlp':62,opt_parse_dcg([],A-A,B,C),B=C),!,true.
write_file_header(A,B,C-D):-!,'$__body__'('src/mlpc.mlp':63,write_file_header(A,B,C-D),A=[E|_]),!,'$__body__'('src/mlpc.mlp':63,
			write_file_header(A,B,C-D),
			C = [ writeln('#!/usr/bin/env swipl'),
			  writeln('% This code is generated by MLP compiler'),
			  format('% source: ~w~n',[A]),
			  writeln(':- use_module(library(chr)).'),
			  writeln(':- initialization(\'$__main\', main).'),
			  writeln('% main wrapper'),
			  writeln('\'$__main\' :-')
			| F
			]),!,'$__body__'('src/mlpc.mlp':63,
			write_file_header(A,B,C-D),
			append_debug(B,F-G)),!,'$__body__'('src/mlpc.mlp':63,
			write_file_header(A,B,C-D),
			G = [ writeln('    current_prolog_flag(argv, Argv),'),
			  format('    main([\'~s\'|Argv]).~n',E),
			  writeln('% runtime predicates'),
			  writeln('% call wrapper'),
			  writeln('\'$__guard__\'(Position, Head, RealGoal) :- '),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal)'),
			  writeln('    -> debug(mlpc, \'[runtime] ~w: ~p\','),
			  writeln('             [Position,'),
			  writeln('              success(Name/Arity, guard, RealGoal)])'),
			  writeln('    ; debug(mlpc, \'[runtime] ~w: ~p\','),
			  writeln('            [Position,'),
			  writeln('             fail(Name/Arity, guard, RealGoal)]), !, fail ).'),
			  writeln('\'$__guard__\'(Position, Head, DispGoal, RealGoal) :- '),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal)'),
			  writeln('    -> debug(mlpc, \'[runtime] ~w: ~p\','),
			  writeln('             [Position,'),
			  writeln('              success(Name/Arity, guard, DispGoal)])'),
			  writeln('    ; debug(mlpc, \'[runtime] ~w: ~p\','),
			  writeln('            [Position,'),
			  writeln('             fail(Name/Arity, guard, RealGoal)]), !, fail ).'),
			  writeln('\'$__body__\'(Position, Head, RealGoal) :-'),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal)'),
			  writeln('    -> debug(mlpc, \'[runtime] ~w: ~p\','),
			  writeln('             [Position,'),
			  writeln('              success(Name/Arity, body, RealGoal)])'),
			  writeln('    ; throw(error(mlp_error(body_failed(RealGoal)),'),
			  writeln('            context(Name / Arity, source(Position)))) ).'),
			  writeln('\'$__body__\'(Position, Head, DispGoal, RealGoal) :-'),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal)'),
			  writeln('    -> debug(mlpc, \'[runtime] ~w: ~p\','),
			  writeln('             [Position,'),
			  writeln('              success(Name/Arity, body, DispGoal)])'),
			  writeln('    ; throw(error(mlp_error(body_failed(DispGoal)),'),
			  writeln('            context(Name / Arity, source(Position)))) ).'),
			  writeln('% generated source codes')
			| D
			]).
append_debug([debug|A],B-C):-!,'$__body__'('src/mlpc.mlp':115,
			append_debug([debug|A],B-C),
			B=[writeln('    debug(mlpc),')|C]).
append_debug(A,B-C):-!,'$__body__'('src/mlpc.mlp':119,append_debug(A,B-C),B=C).
write_term_data([],A):-!,'$__body__'('src/mlpc.mlp':120,write_term_data([],A),A=[told]).
write_term_data([A|B],C):-'$__guard__'('src/mlpc.mlp':122,
			 write_term_data([A|B],C),
			 A=term_data([],_,D,_,_)),!,'$__body__'('src/mlpc.mlp':122,
			write_term_data([A|B],C),
			debug(translate,'~p: ~p',[write_term_data/2,A])),!,'$__body__'('src/mlpc.mlp':122,
			write_term_data([A|B],C),
			C=[writeln(D)|E]),!,'$__body__'('src/mlpc.mlp':122,
			write_term_data([A|B],C),
			write_term_data(B,E)).
write_term_data([A|B],C):-'$__guard__'('src/mlpc.mlp':127,
			 write_term_data([A|B],C),
			 A=term_data(D,E,_,_,_)),!,'$__body__'('src/mlpc.mlp':127,
			write_term_data([A|B],C),
			debug(translate,'~p: ~p',[write_term_data/2,A])),!,'$__body__'('src/mlpc.mlp':127,
			write_term_data([A|B],C),
			C = [ print_term(D,
						 [ variable_names(E),
						   numbervars(true),
						   tab_width(4)
						 ]),
			  writeln('.')
			| F
			]),!,'$__body__'('src/mlpc.mlp':127,
			write_term_data([A|B],C),
			write_term_data(B,F)).
load_term_data([],A-A) :- !.
load_term_data([A|B],C-D):-!,'$__body__'('src/mlpc.mlp':140,
			load_term_data([A|B],C-D),
			open(A,read,E,[encoding(utf8)])),!,'$__body__'('src/mlpc.mlp':140,
			load_term_data([A|B],C-D),
			read_all_terms(A,E,C-F,0)),!,'$__body__'('src/mlpc.mlp':140,load_term_data([A|B],C-D),close(E)),!,'$__body__'('src/mlpc.mlp':140,
			load_term_data([A|B],C-D),
			load_term_data(B,F-D)).
read_all_terms(A,B,C-D,E):-!,'$__body__'('src/mlpc.mlp':145,
			read_all_terms(A,B,C-D,E),
			stream_property(B,position(F))),!,'$__body__'('src/mlpc.mlp':145,
			read_all_terms(A,B,C-D,E),
			read_single_term(A,E,B,G,H,I)),!,'$__body__'('src/mlpc.mlp':145,
			read_all_terms(A,B,C-D,E),
			stream_property(B,position(J))),!,'$__body__'('src/mlpc.mlp':145,
			read_all_terms(A,B,C-D,E),
			read_source_span(A,F,J,K)),!,'$__body__'('src/mlpc.mlp':145,
			read_all_terms(A,B,C-D,E),
			report_singletons(A,E,K,I)),!,'$__body__'('src/mlpc.mlp':145,
			read_all_terms(A,B,C-D,E),
			read_all_terms_aux(G,H,K,A,E,B,J,C-D)).
read_single_term(A,B,C,D,E,F):-'$__guard__'('src/mlpc.mlp':154,
			 read_single_term(A,B,C,D,E,F),
			 read_term(C,
					   D,
					   [ variable_names(E),
						 singletons(F),
						 syntax_errors(dec10)
					   ])),!,true.
read_single_term(A,B,C,D,E,F):-!,'$__body__'('src/mlpc.mlp':161,
			read_single_term(A,B,C,D,E,F),
			format(user_error,
				   '[mlpc] ~a:~d: failed to read term~n',
				   [A,B])).
read_all_terms_aux(A,B,C,D,E,F,G,H-I):-'$__guard__'('src/mlpc.mlp':164,
			 read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			 A=end_of_file),!,'$__body__'('src/mlpc.mlp':164,
			read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			H=I).
read_all_terms_aux(A,B,C,D,E,F,G,H-I):-'$__guard__'('src/mlpc.mlp':167,
			 read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			 A=otherwise),!,'$__body__'('src/mlpc.mlp':167,
			read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			get_line_count(G,J)),!,'$__body__'('src/mlpc.mlp':167,
			read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			read_all_terms(D,F,H-I,J)).
read_all_terms_aux(A,B,C,D,E,F,G,H-I):-!,'$__body__'('src/mlpc.mlp':171,
			read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			H=[term_data(A,B,C,D,E)|J]),!,'$__body__'('src/mlpc.mlp':171,
			read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			get_line_count(G,K)),!,'$__body__'('src/mlpc.mlp':171,
			read_all_terms_aux(A,B,C,D,E,F,G,H-I),
			read_all_terms(D,F,J-I,K)).
read_source_span(A,B,C,D):-!,'$__body__'('src/mlpc.mlp':176,
			read_source_span(A,B,C,D),
			stream_position_data(char_count,B,E)),!,'$__body__'('src/mlpc.mlp':176,
			read_source_span(A,B,C,D),
			stream_position_data(char_count,C,F)),!,'$__body__'('src/mlpc.mlp':176,read_source_span(A,B,C,D),G is F-E),!,'$__body__'('src/mlpc.mlp':176,
			read_source_span(A,B,C,D),
			open(A,read,H,[encoding(utf8)])),!,'$__body__'('src/mlpc.mlp':176,
			read_source_span(A,B,C,D),
			seek(H,E,bof,_)),!,'$__body__'('src/mlpc.mlp':176,
			read_source_span(A,B,C,D),
			read_string(H,G,D)),!,'$__body__'('src/mlpc.mlp':176,read_source_span(A,B,C,D),close(H)).
get_line_count(A,B):-!,'$__body__'('src/mlpc.mlp':185,
			get_line_count(A,B),
			stream_position_data(line_count,A,C)),!,'$__body__'('src/mlpc.mlp':185,get_line_count(A,B),B is C+1).
report_singletons(A,B,C,D):-!,'$__body__'('src/mlpc.mlp':189,
			report_singletons(A,B,C,D),
			filter_singletons(D,E-[])),!,'$__body__'('src/mlpc.mlp':189,
			report_singletons(A,B,C,D),
			report_singletons_aux(A,B,E,C)).
report_singletons_aux(_,_,[],_) :- !.
report_singletons_aux(A,B,C,D):-!,'$__body__'('src/mlpc.mlp':196,
			report_singletons_aux(A,B,C,D),
			format(user_error,
				   '[mlpc] ~a:~d: warning: Singletons ~w in "~w".~n',
				   [A,B,C,D])).
filter_singletons([],A-B):-!,'$__body__'('src/mlpc.mlp':199,filter_singletons([],A-B),A=B).
filter_singletons([A=B|C],D-E):-( '$__guard__'('src/mlpc.mlp':202,
			   filter_singletons([A=B|C],D-E),
			   atom_chars(A,F)),
  '$__guard__'('src/mlpc.mlp':202,
			   filter_singletons([A=B|C],D-E),
			   F=['_'|_])
),!,'$__body__'('src/mlpc.mlp':202,
			filter_singletons([A=B|C],D-E),
			filter_singletons(C,D-E)).
filter_singletons([A=B|C],D-E):-!,'$__body__'('src/mlpc.mlp':207,filter_singletons([A=B|C],D-E),D=[A|F]),!,'$__body__'('src/mlpc.mlp':207,
			filter_singletons([A=B|C],D-E),
			filter_singletons(C,F-E)).
A:=B :- !,'$__body__'('builtin.mlp':0,A:=B,A is B).
iostream(A):-!,'$__body__'('builtin.mlp':3,iostream(A),A=[_|_]),!,'$__body__'('builtin.mlp':3,iostream(A),iostream_loop(A)).
iostream_loop(A):-'$__guard__'('builtin.mlp':7,iostream_loop(A),var(A)),!,'$__body__'('builtin.mlp':7,
			iostream_loop(A),
			'$__freeze__'('builtin.mlp':7,A,iostream_loop(A))).
iostream_loop([A|B]):-'$__guard__'('builtin.mlp':9,iostream_loop([A|B]),var(A)),!,'$__body__'('builtin.mlp':9,
			iostream_loop([A|B]),
			'$__freeze__'('builtin.mlp':9,A,iostream_loop([A|B]))).
iostream_loop([]) :- !.
iostream_loop([told]) :- !.
iostream_loop([write(A)|B]):-!,'$__body__'('builtin.mlp':13,iostream_loop([write(A)|B]),write(A)),!,'$__body__'('builtin.mlp':13,
			iostream_loop([write(A)|B]),
			iostream_loop(B)).
iostream_loop([writeln(A)|B]):-!,'$__body__'('builtin.mlp':14,iostream_loop([writeln(A)|B]),writeln(A)),!,'$__body__'('builtin.mlp':14,
			iostream_loop([writeln(A)|B]),
			iostream_loop(B)).
iostream_loop([write_term(A,B)|C]):-!,'$__body__'('builtin.mlp':15,
			iostream_loop([write_term(A,B)|C]),
			write_term(A,B)),!,'$__body__'('builtin.mlp':15,
			iostream_loop([write_term(A,B)|C]),
			iostream_loop(C)).
iostream_loop([print_term(A,B)|C]):-!,'$__body__'('builtin.mlp':17,
			iostream_loop([print_term(A,B)|C]),
			print_term(A,B)),!,'$__body__'('builtin.mlp':17,
			iostream_loop([print_term(A,B)|C]),
			iostream_loop(C)).
iostream_loop([format(A,B,C)|D]):-!,'$__body__'('builtin.mlp':19,
			iostream_loop([format(A,B,C)|D]),
			format(A,B,C)),!,'$__body__'('builtin.mlp':19,
			iostream_loop([format(A,B,C)|D]),
			iostream_loop(D)).
iostream_loop([format(A,B)|C]):-!,'$__body__'('builtin.mlp':21,
			iostream_loop([format(A,B)|C]),
			format(A,B)),!,'$__body__'('builtin.mlp':21,
			iostream_loop([format(A,B)|C]),
			iostream_loop(C)).
iostream_loop([nl|A]):-!,'$__body__'('builtin.mlp':23,iostream_loop([nl|A]),nl),!,'$__body__'('builtin.mlp':23,iostream_loop([nl|A]),iostream_loop(A)).
iostream_loop([ttyflush|A]):-!,'$__body__'('builtin.mlp':24,iostream_loop([ttyflush|A]),ttyflush),!,'$__body__'('builtin.mlp':24,
			iostream_loop([ttyflush|A]),
			iostream_loop(A)).
iostream_loop([flush(A)|B]):-!,'$__body__'('builtin.mlp':25,iostream_loop([flush(A)|B]),ttyflush),!,'$__body__'('builtin.mlp':25,iostream_loop([flush(A)|B]),A=flushed),!,'$__body__'('builtin.mlp':25,
			iostream_loop([flush(A)|B]),
			iostream_loop(B)).
iostream_loop([read(A)|B]):-!,'$__body__'('builtin.mlp':27,iostream_loop([read(A)|B]),read(A)),!,'$__body__'('builtin.mlp':27,
			iostream_loop([read(A)|B]),
			iostream_loop(B)).
iostream_loop([open(A,B,C,D)|E]):-!,'$__body__'('builtin.mlp':28,
			iostream_loop([open(A,B,C,D)|E]),
			open(A,B,C,D)),!,'$__body__'('builtin.mlp':28,
			iostream_loop([open(A,B,C,D)|E]),
			iostream_loop(E)).
iostream_loop([close(A)|B]):-!,'$__body__'('builtin.mlp':30,iostream_loop([close(A)|B]),close(A)),!,'$__body__'('builtin.mlp':30,
			iostream_loop([close(A)|B]),
			iostream_loop(B)).
iostream_loop([prompt1(A)|B]):-!,'$__body__'('builtin.mlp':32,iostream_loop([prompt1(A)|B]),prompt1(A)),!,'$__body__'('builtin.mlp':32,
			iostream_loop([prompt1(A)|B]),
			iostream_loop(B)).
iostream_loop([read_term(A,B,C)|D]):-!,'$__body__'('builtin.mlp':34,
			iostream_loop([read_term(A,B,C)|D]),
			read_term(A,B,C)),!,'$__body__'('builtin.mlp':34,
			iostream_loop([read_term(A,B,C)|D]),
			iostream_loop(D)).
iostream_loop([A|B]):-!,'$__body__'('builtin.mlp':37,
			iostream_loop([A|B]),
			format(user_error,
				   'error: unknown iostream operation: ~w~n',
				   [A])),!,'$__body__'('builtin.mlp':37,iostream_loop([A|B]),iostream_loop(B)).
chr_post(A) :- !,'$__body__'('builtin.mlp':41,chr_post(A),call(A)).
chr_post_list([]) :- !.
chr_post_list([A|B]):-!,'$__body__'('builtin.mlp':47,chr_post_list([A|B]),chr_post(A)),!,'$__body__'('builtin.mlp':47,chr_post_list([A|B]),chr_post_list(B)).
chr_findall(A,B,C):-!,'$__body__'('builtin.mlp':48,
			chr_findall(A,B,C),
			findall(A,find_chr_constraint(B),C)).
chr_findall(A,B,C,D):-!,'$__body__'('builtin.mlp':50,
			chr_findall(A,B,C,D),
			findall(A,find_chr_constraint(B),C,D)).
chr_findnsols(A,B,C,D):-!,'$__body__'('builtin.mlp':52,
			chr_findnsols(A,B,C,D),
			findnsols(A,B,find_chr_constraint(C),D)).
chr_findnsols(A,B,C,D,E):-!,'$__body__'('builtin.mlp':54,
			chr_findnsols(A,B,C,D,E),
			findnsols(A,B,find_chr_constraint(C),D,E)).
'$__translate__'(A,B):-!,'$__body__'('src/mlpc_runtime.mlp':0,
			'$__translate__'(A,B),
			'$__preprocess_chr__'(A,C)),!,'$__body__'('src/mlpc_runtime.mlp':0,
			'$__translate__'(A,B),
			'$__preprocess_dcg__'(C,D)),!,'$__body__'('src/mlpc_runtime.mlp':0,
			'$__translate__'(A,B),
			'$__translate_aux__'(D,B)).
'$__translate_aux__'([],[]) :- !.
'$__translate_aux__'([term_data([],A,B,C,D)|E],
					 [term_data([],A,B,C,D)|F]):-!,'$__body__'('src/mlpc_runtime.mlp':11,
			'$__translate_aux__'([term_data([],A,B,C,D)|E],
								 [term_data([],A,B,C,D)|F]),
			'$__translate_aux__'(E,F)).
'$__translate_aux__'([term_data((A:-B|C),D,E,F,G)|H],
					 [term_data((A:-I,!,J),D,E,F,G)|K]):-!,'$__body__'('src/mlpc_runtime.mlp':17,
			'$__translate_aux__'([term_data((A:-B|C),D,E,F,G)|H],
								 [term_data((A:-I,!,J),D,E,F,G)|K]),
			debug(translate,
				  '[runtime] ~w: ~p: ~p',
				  [F:G,translate/2,'$__call_guards__'(F:G,A,B,I)])),!,'$__body__'('src/mlpc_runtime.mlp':17,
			'$__translate_aux__'([term_data((A:-B|C),D,E,F,G)|H],
								 [term_data((A:-I,!,J),D,E,F,G)|K]),
			'$__call_guards__'(F:G,A,B,I)),!,'$__body__'('src/mlpc_runtime.mlp':17,
			'$__translate_aux__'([term_data((A:-B|C),D,E,F,G)|H],
								 [term_data((A:-I,!,J),D,E,F,G)|K]),
			debug(translate,
				  '[runtime] ~w: ~p: ~p',
				  [F:G,translate/2,'$__call_goals__'(F:G,A,C,J)])),!,'$__body__'('src/mlpc_runtime.mlp':17,
			'$__translate_aux__'([term_data((A:-B|C),D,E,F,G)|H],
								 [term_data((A:-I,!,J),D,E,F,G)|K]),
			'$__call_goals__'(F:G,A,C,J)),!,'$__body__'('src/mlpc_runtime.mlp':17,
			'$__translate_aux__'([term_data((A:-B|C),D,E,F,G)|H],
								 [term_data((A:-I,!,J),D,E,F,G)|K]),
			'$__translate_aux__'(H,K)).
'$__translate_aux__'([term_data((A:-B),C,D,E,F)|G],
					 [term_data((A:-!,H),C,D,E,F)|I]):-!,'$__body__'('src/mlpc_runtime.mlp':33,
			'$__translate_aux__'([term_data((A:-B),C,D,E,F)|G],
								 [term_data((A:-!,H),C,D,E,F)|I]),
			debug(translate,
				  '[runtime] ~w: ~p: ~p',
				  [E:F,translate/2,'$__call_goals__'(E:F,A,B,H)])),!,'$__body__'('src/mlpc_runtime.mlp':33,
			'$__translate_aux__'([term_data((A:-B),C,D,E,F)|G],
								 [term_data((A:-!,H),C,D,E,F)|I]),
			'$__call_goals__'(E:F,A,B,H)),!,'$__body__'('src/mlpc_runtime.mlp':33,
			'$__translate_aux__'([term_data((A:-B),C,D,E,F)|G],
								 [term_data((A:-!,H),C,D,E,F)|I]),
			'$__translate_aux__'(G,I)).
'$__translate_aux__'([term_data((:-A),B,C,D,E)|F],
					 [term_data((:-A),B,C,D,E)|G]):-!,'$__body__'('src/mlpc_runtime.mlp':44,
			'$__translate_aux__'([term_data((:-A),B,C,D,E)|F],
								 [term_data((:-A),B,C,D,E)|G]),
			debug(translate,
				  '[runtime] ~w: ~p: ~p',
				  [D:E,translate/2,(:-A)])),!,'$__body__'('src/mlpc_runtime.mlp':44,
			'$__translate_aux__'([term_data((:-A),B,C,D,E)|F],
								 [term_data((:-A),B,C,D,E)|G]),
			'$__translate_aux__'(F,G)).
'$__translate_aux__'([term_data(A,B,C,D,E)|F],
					 [term_data((A:-!),B,C,D,E)|G]):-!,'$__body__'('src/mlpc_runtime.mlp':53,
			'$__translate_aux__'([term_data(A,B,C,D,E)|F],
								 [term_data((A:-!),B,C,D,E)|G]),
			debug(translate,'[runtime] ~w: ~p: ~p',[D:E,translate/2,A])),!,'$__body__'('src/mlpc_runtime.mlp':53,
			'$__translate_aux__'([term_data(A,B,C,D,E)|F],
								 [term_data((A:-!),B,C,D,E)|G]),
			'$__translate_aux__'(F,G)).
'$__translate_aux__'([term_data(A,B,C,D,E)|F],
					 [term_data([],B,C,D,E)|G]):-!,'$__body__'('src/mlpc_runtime.mlp':62,
			'$__translate_aux__'([term_data(A,B,C,D,E)|F],
								 [term_data([],B,C,D,E)|G]),
			debug(translate,'[runtime] ~w: ~p: ~p',[D:E,translate/2,A])),!,'$__body__'('src/mlpc_runtime.mlp':62,
			'$__translate_aux__'([term_data(A,B,C,D,E)|F],
								 [term_data([],B,C,D,E)|G]),
			'$__translate_aux__'(F,G)).
'$__call_guards__'(A,B,(C,D),(E,F)):-!,'$__body__'('src/mlpc_runtime.mlp':70,
			'$__call_guards__'(A,B,(C,D),(E,F)),
			'$__call_guards__'(A,B,C,E)),!,'$__body__'('src/mlpc_runtime.mlp':70,
			'$__call_guards__'(A,B,(C,D),(E,F)),
			'$__call_guards__'(A,B,D,F)).
'$__call_guards__'(A,B,(C->D),(E->F)):-!,'$__body__'('src/mlpc_runtime.mlp':74,
			'$__call_guards__'(A,B,(C->D),(E->F)),
			'$__call_guards__'(A,B,C,E)),!,'$__body__'('src/mlpc_runtime.mlp':74,
			'$__call_guards__'(A,B,(C->D),(E->F)),
			'$__call_guards__'(A,B,D,F)).
'$__call_guards__'(A,B,(C;D),(E;F)):-!,'$__body__'('src/mlpc_runtime.mlp':77,
			'$__call_guards__'(A,B,(C;D),(E;F)),
			'$__call_guards__'(A,B,C,E)),!,'$__body__'('src/mlpc_runtime.mlp':77,
			'$__call_guards__'(A,B,(C;D),(E;F)),
			'$__call_guards__'(A,B,D,F)).
'$__call_guards__'(A,B,true,C):-!,'$__body__'('src/mlpc_runtime.mlp':80,
			'$__call_guards__'(A,B,true,C),
			C=true).
'$__call_guards__'(A,B,!,C):-!,'$__body__'('src/mlpc_runtime.mlp':81,'$__call_guards__'(A,B,!,C),C=!).
'$__call_guards__'(A,B,var(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':82,
			'$__call_guards__'(A,B,var(C),D),
			D = '$__guard__'(A,B,var(C))).
'$__call_guards__'(A,B,nonvar(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':84,
			'$__call_guards__'(A,B,nonvar(C),D),
			D = '$__guard__'(A,B,nonvar(C))).
'$__call_guards__'(A,B,integer(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':86,
			'$__call_guards__'(A,B,integer(C),D),
			D = '$__guard__'(A,B,integer(C))).
'$__call_guards__'(A,B,C=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':88,
			'$__call_guards__'(A,B,C=D,E),
			E = '$__guard__'(A,B,C=D)).
'$__call_guards__'(A,B,C=..D,E):-!,'$__body__'('src/mlpc_runtime.mlp':90,
			'$__call_guards__'(A,B,C=..D,E),
			E = '$__guard__'(A,B,C=..D)).
'$__call_guards__'(A,B,C is D,E):-!,'$__body__'('src/mlpc_runtime.mlp':92,
			'$__call_guards__'(A,B,C is D,E),
			E = '$__guard__'(A,B,C is D)).
'$__call_guards__'(A,B,C:=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':94,
			'$__call_guards__'(A,B,C:=D,E),
			E = '$__guard__'(A,B,C is D)).
'$__call_guards__'(A,B,C=\=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':96,
			'$__call_guards__'(A,B,C=\=D,E),
			E = '$__guard__'(A,B,C=\=D)).
'$__call_guards__'(A,B,C=:=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':98,
			'$__call_guards__'(A,B,C=:=D,E),
			E = '$__guard__'(A,B,C=:=D)).
'$__call_guards__'(A,B,C<D,E):-!,'$__body__'('src/mlpc_runtime.mlp':100,
			'$__call_guards__'(A,B,C<D,E),
			E = '$__guard__'(A,B,C<D)).
'$__call_guards__'(A,B,C>D,E):-!,'$__body__'('src/mlpc_runtime.mlp':102,
			'$__call_guards__'(A,B,C>D,E),
			E = '$__guard__'(A,B,C>D)).
'$__call_guards__'(A,B,C=<D,E):-!,'$__body__'('src/mlpc_runtime.mlp':104,
			'$__call_guards__'(A,B,C=<D,E),
			E = '$__guard__'(A,B,C=<D)).
'$__call_guards__'(A,B,C>=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':106,
			'$__call_guards__'(A,B,C>=D,E),
			E = '$__guard__'(A,B,C>=D)).
'$__call_guards__'(A,B,prolog(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':108,
			'$__call_guards__'(A,B,prolog(C),D),
			D = '$__guard__'(A,B,C)).
'$__call_guards__'(A,B,call(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':110,
			'$__call_guards__'(A,B,call(C),D),
			D = '$__guard__'(A,B,'$__call__'(A,C))).
'$__call_guards__'(A,B,freeze(C,D),E):-!,'$__body__'('src/mlpc_runtime.mlp':112,
			'$__call_guards__'(A,B,freeze(C,D),E),
			E = '$__guard__'(A,B,'$__freeze__'(A,C,D))).
'$__call_guards__'(A,B,catch(C,D,E),F):-!,'$__body__'('src/mlpc_runtime.mlp':114,
			'$__call_guards__'(A,B,catch(C,D,E),F),
			F = '$__guard__'(A,B,'$__catch__'(A,C,D,E))).
'$__call_guards__'(A,B,abolish(C,D),E):-!,'$__body__'('src/mlpc_runtime.mlp':116,
			'$__call_guards__'(A,B,abolish(C,D),E),
			E = '$__guard__'(A,B,'$__abolish__'(A,C,D))).
'$__call_guards__'(A,B,asserta(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':118,
			'$__call_guards__'(A,B,asserta(C),D),
			D = '$__guard__'(A,B,'$__asserta__'(A,C))).
'$__call_guards__'(A,B,assertz(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':120,
			'$__call_guards__'(A,B,assertz(C),D),
			D = '$__guard__'(A,B,'$__assertz__'(A,C))).
'$__call_guards__'(A,B,C,D):-!,'$__body__'('src/mlpc_runtime.mlp':122,
			'$__call_guards__'(A,B,C,D),
			D = '$__guard__'(A,B,C)).
'$__call_goals__'(A,B,(C,D),(E,!,F)):-!,'$__body__'('src/mlpc_runtime.mlp':124,
			'$__call_goals__'(A,B,(C,D),(E,!,F)),
			'$__call_goals__'(A,B,C,E)),!,'$__body__'('src/mlpc_runtime.mlp':124,
			'$__call_goals__'(A,B,(C,D),(E,!,F)),
			'$__call_goals__'(A,B,D,F)).
'$__call_goals__'(A,B,(C->D),E):-!,'$__body__'('src/mlpc_runtime.mlp':128,
			'$__call_goals__'(A,B,(C->D),E),
			functor(B,F,G)),!,'$__body__'('src/mlpc_runtime.mlp':128,
			'$__call_goals__'(A,B,(C->D),E),
			throw(error(crash(F/G,compile,'"->" not allowed in body'),
						context(A,B)))).
'$__call_goals__'(A,B,(C;D),E):-!,'$__body__'('src/mlpc_runtime.mlp':132,
			'$__call_goals__'(A,B,(C;D),E),
			functor(B,F,G)),!,'$__body__'('src/mlpc_runtime.mlp':132,
			'$__call_goals__'(A,B,(C;D),E),
			throw(error(crash(F/G,compile,'";" not allowed in body'),
						context(A,B)))).
'$__call_goals__'(A,B,!,C):-!,'$__body__'('src/mlpc_runtime.mlp':136,
			'$__call_goals__'(A,B,!,C),
			functor(B,D,E)),!,'$__body__'('src/mlpc_runtime.mlp':136,
			'$__call_goals__'(A,B,!,C),
			throw(error(crash(D/E,compile,'"!" not allowed in body'),
						context(A,B)))).
'$__call_goals__'(_,_,true,true) :- !.
'$__call_goals__'(A,B,C=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':141,
			'$__call_goals__'(A,B,C=D,E),
			E = '$__body__'(A,B,C=D)).
'$__call_goals__'(A,B,C:=D,E):-!,'$__body__'('src/mlpc_runtime.mlp':143,
			'$__call_goals__'(A,B,C:=D,E),
			E = '$__body__'(A,B,C is D)).
'$__call_goals__'(A,B,C is D,E):-!,'$__body__'('src/mlpc_runtime.mlp':145,
			'$__call_goals__'(A,B,C is D,E),
			E = '$__body__'(A,B,C is D)).
'$__call_goals__'(A,B,C=..D,E):-!,'$__body__'('src/mlpc_runtime.mlp':147,
			'$__call_goals__'(A,B,C=..D,E),
			E = '$__body__'(A,B,C=..D)).
'$__call_goals__'(A,B,prolog(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':149,
			'$__call_goals__'(A,B,prolog(C),D),
			D = '$__body__'(A,B,C)).
'$__call_goals__'(A,B,call(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':151,
			'$__call_goals__'(A,B,call(C),D),
			D = '$__body__'(A,B,'$__call__'(A,C))).
'$__call_goals__'(A,B,freeze(C,D),E):-!,'$__body__'('src/mlpc_runtime.mlp':153,
			'$__call_goals__'(A,B,freeze(C,D),E),
			E = '$__body__'(A,B,'$__freeze__'(A,C,D))).
'$__call_goals__'(A,B,catch(C,D,E),F):-!,'$__body__'('src/mlpc_runtime.mlp':155,
			'$__call_goals__'(A,B,catch(C,D,E),F),
			F = '$__body__'(A,B,'$__catch__'(A,C,D,E))).
'$__call_goals__'(A,B,abolish(C,D),E):-!,'$__body__'('src/mlpc_runtime.mlp':157,
			'$__call_goals__'(A,B,abolish(C,D),E),
			E = '$__body__'(A,B,'$__abolish__'(A,C,D))).
'$__call_goals__'(A,B,asserta(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':159,
			'$__call_goals__'(A,B,asserta(C),D),
			D = '$__body__'(A,B,'$__asserta__'(A,C))).
'$__call_goals__'(A,B,assertz(C),D):-!,'$__body__'('src/mlpc_runtime.mlp':161,
			'$__call_goals__'(A,B,assertz(C),D),
			D = '$__body__'(A,B,'$__assertz__'(A,C))).
'$__call_goals__'(A,B,C,D):-!,'$__body__'('src/mlpc_runtime.mlp':163,
			'$__call_goals__'(A,B,C,D),
			D = '$__body__'(A,B,C)).
'$__rename__'(A,call(B),C):-!,'$__body__'('src/mlpc_runtime.mlp':165,
			'$__rename__'(A,call(B),C),
			'$__call_goals__'(A,call(B),B,C)).
'$__rename__'(A,freeze(B,C),D):-!,'$__body__'('src/mlpc_runtime.mlp':168,
			'$__rename__'(A,freeze(B,C),D),
			'$__call_goals__'(A,freeze(C),C,E)),!,'$__body__'('src/mlpc_runtime.mlp':168,
			'$__rename__'(A,freeze(B,C),D),
			D=freeze(B,E)).
'$__rename__'(A,catch(B,C,D),E):-!,'$__body__'('src/mlpc_runtime.mlp':171,
			'$__rename__'(A,catch(B,C,D),E),
			'$__call_goals__'(A,freeze(B),B,F)),!,'$__body__'('src/mlpc_runtime.mlp':171,
			'$__rename__'(A,catch(B,C,D),E),
			'$__call_goals__'(A,freeze(D),B,G)),!,'$__body__'('src/mlpc_runtime.mlp':171,
			'$__rename__'(A,catch(B,C,D),E),
			E=catch(F,C,G)).
'$__rename__'(A,prolog(B),C):-!,'$__body__'('src/mlpc_runtime.mlp':175,
			'$__rename__'(A,prolog(B),C),
			C=B).
'$__rename__'(_,A,A) :- !.
'$__call__'(A,B):-!,'$__body__'('src/mlpc_runtime.mlp':178,
			'$__call__'(A,B),
			'$__rename__'(A,B,C)),!,'$__body__'('src/mlpc_runtime.mlp':178,
			'$__call__'(A,B),
			debug(translate,'[runtime] ~w: ~p: ~p',[A,call/1,call(C)])),!,'$__body__'('src/mlpc_runtime.mlp':178,'$__call__'(A,B),call(C)).
'$__freeze__'(A,B,C):-!,'$__body__'('src/mlpc_runtime.mlp':184,
			'$__freeze__'(A,B,C),
			debug(translate,
				  '[runtime] ~w: ~p: ~p',
				  [A,freeze/1,freeze(B,C)])),!,'$__body__'('src/mlpc_runtime.mlp':184,
			'$__freeze__'(A,B,C),
			freeze(B,('$__rename__'(A,C,D),'$__call__'(A,D)))).
'$__catch__'(A,B,C,D):-!,'$__body__'('src/mlpc_runtime.mlp':190,
			'$__catch__'(A,B,C,D),
			debug(translate,
				  '[runtime] ~w: ~p: ~p',
				  [A,catch/1,catch(A,B,C,D)])),!,'$__body__'('src/mlpc_runtime.mlp':190,
			'$__catch__'(A,B,C,D),
			catch(('$__rename__'(A,B,E),'$__call__'(A,E)),
				  C,
				  ('$__rename__'(A,D,F),'$__call__'(A,F)))).
'$__abolish__'(A,B,C):-!,'$__body__'('src/mlpc_runtime.mlp':199,
			'$__abolish__'(A,B,C),
			debug(translate,'[runtime] ~w: ~p: ~p',[A,abolish/1,B/C])),!,'$__body__'('src/mlpc_runtime.mlp':199,
			'$__abolish__'(A,B,C),
			abolish(B,C)).
'$__asserta__'(A:B,C):-!,'$__body__'('src/mlpc_runtime.mlp':203,
			'$__asserta__'(A:B,C),
			'$__translate__'([term_data(C,[],D,A,B)],
							 [term_data(E,_,D,A,B)])),!,'$__body__'('src/mlpc_runtime.mlp':203,
			'$__asserta__'(A:B,C),
			debug(translate,'[runtime] ~w: ~p: ~p',[A:B,asserta/1,E])),!,'$__body__'('src/mlpc_runtime.mlp':203,
			'$__asserta__'(A:B,C),
			asserta(E)).
'$__assertz__'(A:B,C):-!,'$__body__'('src/mlpc_runtime.mlp':209,
			'$__assertz__'(A:B,C),
			'$__translate__'([term_data(C,[],D,A,B)],
							 [term_data(E,_,D,A,B)])),!,'$__body__'('src/mlpc_runtime.mlp':209,
			'$__assertz__'(A:B,C),
			debug(translate,'[runtime] ~w: ~p: ~p',[A:B,assertz/1,E])),!,'$__body__'('src/mlpc_runtime.mlp':209,
			'$__assertz__'(A:B,C),
			assertz(E)).
'$__preprocess_chr__'([],[]) :- !.
'$__preprocess_chr__'([term_data(A,B,C,D,E)|F],
					  [term_data(G,B,C,D,E)|H]):-!,'$__body__'('src/mlpc_preprocess.mlp':7,
			'$__preprocess_chr__'([term_data(A,B,C,D,E)|F],
								  [term_data(G,B,C,D,E)|H]),
			'$__preprocess_chr_term__'(A,G)),!,'$__body__'('src/mlpc_preprocess.mlp':7,
			'$__preprocess_chr__'([term_data(A,B,C,D,E)|F],
								  [term_data(G,B,C,D,E)|H]),
			debug(preprocess,
				  '~p: ~p',
				  [ '$__preprocess_chr__'/2,
					'$__preprocess_chr_term__'(A,G)
				  ])),!,'$__body__'('src/mlpc_preprocess.mlp':7,
			'$__preprocess_chr__'([term_data(A,B,C,D,E)|F],
								  [term_data(G,B,C,D,E)|H]),
			'$__preprocess_chr__'(F,H)).
'$__preprocess_chr_term__'((_==>_),[]) :- !.
'$__preprocess_chr_term__'((_@_==>_),[]) :- !.
'$__preprocess_chr_term__'((_<=>_),[]) :- !.
'$__preprocess_chr_term__'((_@_<=>_),[]) :- !.
'$__preprocess_chr_term__'(A,A) :- !.
'$__preprocess_dcg__'([],[]) :- !.
'$__preprocess_dcg__'([term_data(A,B,C,D,E)|F],
					  [term_data(G,B,C,D,E)|H]):-!,'$__body__'('src/mlpc_preprocess.mlp':29,
			'$__preprocess_dcg__'([term_data(A,B,C,D,E)|F],
								  [term_data(G,B,C,D,E)|H]),
			'$__preprocess_dcg_term__'(A,G)),!,'$__body__'('src/mlpc_preprocess.mlp':29,
			'$__preprocess_dcg__'([term_data(A,B,C,D,E)|F],
								  [term_data(G,B,C,D,E)|H]),
			'$__preprocess_dcg__'(F,H)).
'$__preprocess_dcg_term__'((A-->B|C),D):-( '$__guard__'('src/mlpc_preprocess.mlp':36,
			   '$__preprocess_dcg_term__'((A-->B|C),D),
			   E=(A-->B'|'C)),
  '$__guard__'('src/mlpc_preprocess.mlp':36,
			   '$__preprocess_dcg_term__'((A-->B|C),D),
			   '$__may_be_stream__'(B)),
  '$__guard__'('src/mlpc_preprocess.mlp':36,
			   '$__preprocess_dcg_term__'((A-->B|C),D),
			   '$__may_be_stream__'(C))
),!,'$__body__'('src/mlpc_preprocess.mlp':36,
			'$__preprocess_dcg_term__'((A-->B|C),D),
			debug(preprocess,
				  '~p: ~p',
				  [preprocess_term/2,may_be_stream('Guard'=B)])),!,'$__body__'('src/mlpc_preprocess.mlp':36,
			'$__preprocess_dcg_term__'((A-->B|C),D),
			throw(error(invalid_predicate(E)))).
'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)):-( '$__guard__'('src/mlpc_preprocess.mlp':41,
			   '$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   G=(A-->B'|'C)),
  '$__guard__'('src/mlpc_preprocess.mlp':41,
			   '$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   '$__may_be_stream__'(B))
),!,'$__body__'('src/mlpc_preprocess.mlp':41,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			'$__preprocess_dcg_stream__'(G,B,H-I,E)),!,'$__body__'('src/mlpc_preprocess.mlp':41,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			debug(preprocess,
				  '~p: ~p',
				  [ preprocess_term/2,
					'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F))
				  ])),!,'$__body__'('src/mlpc_preprocess.mlp':41,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			A=..[J|K]),!,'$__body__'('src/mlpc_preprocess.mlp':41,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			append(K,[H,I],L)),!,'$__body__'('src/mlpc_preprocess.mlp':41,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			D=..[J|L]),!,'$__body__'('src/mlpc_preprocess.mlp':41,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			F=C).
'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)):-( '$__guard__'('src/mlpc_preprocess.mlp':53,
			   '$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   G=(A-->B'|'C)),
  '$__guard__'('src/mlpc_preprocess.mlp':53,
			   '$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   '$__may_be_stream__'(C))
),!,'$__body__'('src/mlpc_preprocess.mlp':53,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			'$__preprocess_dcg_stream__'(G,C,H-I,F)),!,'$__body__'('src/mlpc_preprocess.mlp':53,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			A=..[J|K]),!,'$__body__'('src/mlpc_preprocess.mlp':53,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			append(K,[H,I],L)),!,'$__body__'('src/mlpc_preprocess.mlp':53,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			debug(preprocess,
				  '~p: ~p',
				  [ preprocess_term/2,
					'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F))
				  ])),!,'$__body__'('src/mlpc_preprocess.mlp':53,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			D=..[J|L]),!,'$__body__'('src/mlpc_preprocess.mlp':53,
			'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			E=B).
'$__preprocess_dcg_term__'((A-->B),(C:-D)):-( '$__guard__'('src/mlpc_preprocess.mlp':65,
			   '$__preprocess_dcg_term__'((A-->B),(C:-D)),
			   E=(A-->B)),
  '$__guard__'('src/mlpc_preprocess.mlp':65,
			   '$__preprocess_dcg_term__'((A-->B),(C:-D)),
			   '$__may_be_stream__'(B))
),!,'$__body__'('src/mlpc_preprocess.mlp':65,
			'$__preprocess_dcg_term__'((A-->B),(C:-D)),
			'$__preprocess_dcg_stream__'(E,B,F-G,D)),!,'$__body__'('src/mlpc_preprocess.mlp':65,
			'$__preprocess_dcg_term__'((A-->B),(C:-D)),
			debug(preprocess,
				  '~p: ~p',
				  [ preprocess_term/2,
					'$__preprocess_dcg_term__'((A-->B),(C:-D))
				  ])),!,'$__body__'('src/mlpc_preprocess.mlp':65,
			'$__preprocess_dcg_term__'((A-->B),(C:-D)),
			A=..[H|I]),!,'$__body__'('src/mlpc_preprocess.mlp':65,
			'$__preprocess_dcg_term__'((A-->B),(C:-D)),
			append(I,[F,G],J)),!,'$__body__'('src/mlpc_preprocess.mlp':65,
			'$__preprocess_dcg_term__'((A-->B),(C:-D)),
			C=..[H|J]).
'$__preprocess_dcg_term__'(A,A) :- !.
'$__may_be_stream__'(A):-( '$__guard__'('src/mlpc_preprocess.mlp':78,
			   '$__may_be_stream__'(A),
			   '$__may_be_stream__'(A,false,B)),
  '$__guard__'('src/mlpc_preprocess.mlp':78,
			   '$__may_be_stream__'(A),
			   B=true)
),!,true.
'$__may_be_stream__'(({A},B),C,D):-!,'$__body__'('src/mlpc_preprocess.mlp':80,
			'$__may_be_stream__'(({A},B),C,D),
			D=true).
'$__may_be_stream__'(([],A),B,C):-!,'$__body__'('src/mlpc_preprocess.mlp':81,
			'$__may_be_stream__'(([],A),B,C),
			C=true).
'$__may_be_stream__'(([A|B],C),D,E):-!,'$__body__'('src/mlpc_preprocess.mlp':82,
			'$__may_be_stream__'(([A|B],C),D,E),
			E=true).
'$__may_be_stream__'((A,B),C,D):-!,'$__body__'('src/mlpc_preprocess.mlp':83,
			'$__may_be_stream__'((A,B),C,D),
			'$__may_be_stream__'(B,C,D)).
'$__may_be_stream__'({A},B,C):-!,'$__body__'('src/mlpc_preprocess.mlp':84,
			'$__may_be_stream__'({A},B,C),
			C=true).
'$__may_be_stream__'([],A,B):-!,'$__body__'('src/mlpc_preprocess.mlp':85,
			'$__may_be_stream__'([],A,B),
			B=true).
'$__may_be_stream__'([A|B],C,D):-!,'$__body__'('src/mlpc_preprocess.mlp':86,
			'$__may_be_stream__'([A|B],C,D),
			D=true).
'$__may_be_stream__'(A,B,C):-!,'$__body__'('src/mlpc_preprocess.mlp':88,
			'$__may_be_stream__'(A,B,C),
			C=B).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,F):-'$__guard__'('src/mlpc_preprocess.mlp':89,
			 '$__preprocess_dcg_stream__'(A,(B,C),D-E,F),
			 B=[]),!,'$__body__'('src/mlpc_preprocess.mlp':89,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,F),
			'$__preprocess_dcg_stream__'(A,C,D-E,F)).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)):-'$__guard__'('src/mlpc_preprocess.mlp':93,
			 '$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			 B=[_|_]),!,'$__body__'('src/mlpc_preprocess.mlp':93,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__extend_list__'(B,H-I)),!,'$__body__'('src/mlpc_preprocess.mlp':93,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			F=(D=H)),!,'$__body__'('src/mlpc_preprocess.mlp':93,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__preprocess_dcg_stream__'(A,C,I-E,G)).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)):-'$__guard__'('src/mlpc_preprocess.mlp':97,
			 '$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			 B={H}),!,'$__body__'('src/mlpc_preprocess.mlp':97,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			F=H),!,'$__body__'('src/mlpc_preprocess.mlp':97,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__preprocess_dcg_stream__'(A,C,D-E,G)).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)):-'$__guard__'('src/mlpc_preprocess.mlp':100,
			 '$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			 B=..[H|I]),!,'$__body__'('src/mlpc_preprocess.mlp':100,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			append(I,[D,J],K)),!,'$__body__'('src/mlpc_preprocess.mlp':100,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			F=..[H|K]),!,'$__body__'('src/mlpc_preprocess.mlp':100,
			'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__preprocess_dcg_stream__'(A,C,J-E,G)).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('src/mlpc_preprocess.mlp':104,
			 '$__preprocess_dcg_stream__'(A,B,C-D,E),
			 B=[]),!,'$__body__'('src/mlpc_preprocess.mlp':104,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			E=(C=D)).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('src/mlpc_preprocess.mlp':106,
			 '$__preprocess_dcg_stream__'(A,B,C-D,E),
			 B=[_|_]),!,'$__body__'('src/mlpc_preprocess.mlp':106,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			'$__extend_list__'(B,F-D)),!,'$__body__'('src/mlpc_preprocess.mlp':106,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			E=(C=F)).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('src/mlpc_preprocess.mlp':109,
			 '$__preprocess_dcg_stream__'(A,B,C-D,E),
			 B={F}),!,'$__body__'('src/mlpc_preprocess.mlp':109,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			E=F),!,'$__body__'('src/mlpc_preprocess.mlp':109,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			C=D).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('src/mlpc_preprocess.mlp':111,
			 '$__preprocess_dcg_stream__'(A,B,C-D,E),
			 B=..[F|G]),!,'$__body__'('src/mlpc_preprocess.mlp':111,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			append(G,[C,D],H)),!,'$__body__'('src/mlpc_preprocess.mlp':111,
			'$__preprocess_dcg_stream__'(A,B,C-D,E),
			E=..[F|H]).
'$__preprocess_dcg_stream__'(A,(B,C),D,E):-!,'$__body__'('src/mlpc_preprocess.mlp':115,
			'$__preprocess_dcg_stream__'(A,(B,C),D,E),
			throw(error(invalid_predicate(A,B)))).
'$__preprocess_dcg_stream__'(A,B,C,D):-!,'$__body__'('src/mlpc_preprocess.mlp':117,
			'$__preprocess_dcg_stream__'(A,B,C,D),
			throw(error(invalid_predicate(A,B)))).
'$__extend_list__'([],A-A) :- !.
'$__extend_list__'([A|B],C-D):-!,'$__body__'('src/mlpc_preprocess.mlp':121,
			'$__extend_list__'([A|B],C-D),
			C=[A|E]),!,'$__body__'('src/mlpc_preprocess.mlp':121,
			'$__extend_list__'([A|B],C-D),
			'$__extend_list__'(B,E-D)).
