#!/usr/bin/env swipl
% This code is generated by MLP compiler
% source: [src/mlpc.mlp,builtin.mlp,src/mlpc_runtime.mlp,src/mlpc_preprocess.mlp]
:- initialization('$__main', main).
% main wrapper
'$__main' :-
    current_prolog_flag(argv, Argv),
    main(['src/mlpc.mlp'|Argv]).
% runtime predicates
% call wrapper
'$__guard__'(Head, RealGoal) :- 
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, guard, RealGoal)])
    ; debug(mlpc, '~p', [fail(Name/Arity, guard, RealGoal)]), !, fail ).
'$__guard__'(Head, DispGoal, RealGoal) :- 
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, guard, DispGoal)])
    ; debug(mlpc, '~p', [fail(Name/Arity, guard, RealGoal)]), !, fail ).
'$__body__'(Head, RealGoal) :-
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, body, RealGoal)])
    ; throw(error(crash(Name/Arity, RealGoal),
                  context(Head, RealGoal))) ).
'$__body__'(Head, DispGoal, RealGoal) :-
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, body, DispGoal)])
    ; throw(error(crash(Name/Arity, DispGoal),
            context(Head, DispGoal))) ).
% generated source codes
% generated source codes
main([A|B]):-!,'$__body__'(main([A|B]),debug(main,'~p: ~p',[main/1,parse_args])),!,'$__body__'(main([A|B]),parse_args(B,C,D-[])),!,'$__body__'(main([A|B]),append_runtime_sources(C,E)),!,'$__body__'(main([A|B]),load_term_data(E,F-[])),!,'$__body__'(main([A|B]),debug(main,'~p: ~p',[main/1,translate])),!,'$__body__'(main([A|B]),'$__translate__'(F,G)),!,'$__body__'(main([A|B]),
			debug(main,'~p: ~p',[main/1,write_file_header])),!,'$__body__'(main([A|B]),iostream(H)),!,'$__body__'(main([A|B]),write_file_header(E,D,H-I)),!,'$__body__'(main([A|B]),debug(main,'~p: ~p',[main/1,write_term_data])),!,'$__body__'(main([A|B]),write_term_data(G,I)),!,'$__body__'(main([A|B]),debug(main,'~p: ~p',[main/1,done])).
append_runtime_sources([],A):-!,'$__body__'(append_runtime_sources([],A),
			A=['src/mlpc_runtime.mlp','src/mlpc_preprocess.mlp']).
append_runtime_sources([A|B],C):-'$__guard__'(append_runtime_sources([A|B],C),A='src/mlpc_runtime.mlp'),!,'$__body__'(append_runtime_sources([A|B],C),
			append_runtime_sources(B,C)).
append_runtime_sources([A|B],C):-'$__guard__'(append_runtime_sources([A|B],C),
			 A='src/mlpc_preprocess.mlp'),!,'$__body__'(append_runtime_sources([A|B],C),
			append_runtime_sources(B,C)).
append_runtime_sources([A|B],C):-!,'$__body__'(append_runtime_sources([A|B],C),C=[A|D]),!,'$__body__'(append_runtime_sources([A|B],C),
			append_runtime_sources(B,D)).
parse_args(A,B,C-D):-!,'$__body__'(parse_args(A,B,C-D),phrase(opt_parse_dcg(B,C-D),A,[])).
opt_parse_dcg([],A-A,B,C):-'$__guard__'(opt_parse_dcg([],A-A,B,C),B=['-h'|C]),!,'$__body__'(opt_parse_dcg([],A-A,B,C),
			iostream([writeln('usage: mlpc_opt <SourceFile..>'),told])).
opt_parse_dcg(A,[debug|B]-C,D,E):-( '$__guard__'(opt_parse_dcg(A,[debug|B]-C,D,E),D=['-d'|F]),
  '$__guard__'(opt_parse_dcg(A,[debug|B]-C,D,E),
			   opt_parse_dcg(A,B-C,F,E))
),!,true.
opt_parse_dcg([A|B],C-D,E,F):-( '$__guard__'(opt_parse_dcg([A|B],C-D,E,F),E=[A|G]),
  '$__guard__'(opt_parse_dcg([A|B],C-D,E,F),opt_parse_dcg(B,C-D,G,F))
),!,true.
opt_parse_dcg([],A-A,B,C):-'$__guard__'(opt_parse_dcg([],A-A,B,C),B=C),!,true.
write_file_header(A,B,C-D):-!,'$__body__'(write_file_header(A,B,C-D),A=[E|_]),!,'$__body__'(write_file_header(A,B,C-D),
			C = [ writeln('#!/usr/bin/env swipl'),
			  writeln('% This code is generated by MLP compiler'),
			  format('% source: ~w~n',[A]),
			  writeln(':- initialization(\'$__main\', main).'),
			  writeln('% main wrapper'),
			  writeln('\'$__main\' :-')
			| F
			]),!,'$__body__'(write_file_header(A,B,C-D),append_debug(B,F-G)),!,'$__body__'(write_file_header(A,B,C-D),
			G = [ writeln('    current_prolog_flag(argv, Argv),'),
			  format('    main([\'~s\'|Argv]).~n',E),
			  writeln('% runtime predicates'),
			  writeln('% call wrapper'),
			  writeln('\'$__guard__\'(Head, RealGoal) :- '),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, guard, RealGoal)])'),
			  writeln('    ; debug(mlpc, \'~p\', [fail(Name/Arity, guard, RealGoal)]), !, fail ).'),
			  writeln('\'$__guard__\'(Head, DispGoal, RealGoal) :- '),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, guard, DispGoal)])'),
			  writeln('    ; debug(mlpc, \'~p\', [fail(Name/Arity, guard, RealGoal)]), !, fail ).'),
			  writeln('\'$__body__\'(Head, RealGoal) :-'),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, body, RealGoal)])'),
			  writeln('    ; throw(error(crash(Name/Arity, RealGoal),'),
			  writeln('                  context(Head, RealGoal))) ).'),
			  writeln('\'$__body__\'(Head, DispGoal, RealGoal) :-'),
			  writeln('    functor(Head, Name, Arity),'),
			  writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, body, DispGoal)])'),
			  writeln('    ; throw(error(crash(Name/Arity, DispGoal),'),
			  writeln('            context(Head, DispGoal))) ).'),
			  writeln('% generated source codes'),
			  writeln('% generated source codes')
			| D
			]).
append_debug([debug|A],B-C):-!,'$__body__'(append_debug([debug|A],B-C),
			B=[writeln('    debug(mlpc),')|C]).
append_debug(A,B-C) :- !,'$__body__'(append_debug(A,B-C),B=C).
write_term_data([],A) :- !,'$__body__'(write_term_data([],A),A=[told]).
write_term_data([A|B],C):-'$__guard__'(write_term_data([A|B],C),A=term_data(D,E)),!,'$__body__'(write_term_data([A|B],C),
			C = [ print_term(D,[variable_names(E),tab_width(4)]),
			  writeln('.')
			| F
			]),!,'$__body__'(write_term_data([A|B],C),write_term_data(B,F)).
load_term_data([],A-A) :- !.
load_term_data([A|B],C-D):-!,'$__body__'(load_term_data([A|B],C-D),iostream(E)),!,'$__body__'(load_term_data([A|B],C-D),
			E=[open(A,read,F,[encoding(utf8)])|G]),!,'$__body__'(load_term_data([A|B],C-D),read_all_terms(G-H,F,C-I)),!,'$__body__'(load_term_data([A|B],C-D),H=[close(F),told]),!,'$__body__'(load_term_data([A|B],C-D),load_term_data(B,I-D)).
read_all_terms(A-B,C,D-E):-!,'$__body__'(read_all_terms(A-B,C,D-E),
			A = [ read_term(C,
						F,
						[ variable_names(G),
						  singletons(H),
						  syntax_errors(dec10)
						])
			| I
			]),!,'$__body__'(read_all_terms(A-B,C,D-E),report_singletons(F,G,H,I-J)),!,'$__body__'(read_all_terms(A-B,C,D-E),
			read_all_terms_aux(F,G,J-B,C,D-E)).
read_all_terms_aux(A,B,C-D,E,F-G):-'$__guard__'(read_all_terms_aux(A,B,C-D,E,F-G),A=end_of_file),!,'$__body__'(read_all_terms_aux(A,B,C-D,E,F-G),C=D),!,'$__body__'(read_all_terms_aux(A,B,C-D,E,F-G),F=G).
read_all_terms_aux(A,B,C-D,E,F-G):-'$__guard__'(read_all_terms_aux(A,B,C-D,E,F-G),A=otherwise),!,'$__body__'(read_all_terms_aux(A,B,C-D,E,F-G),
			read_all_terms(C-D,E,F-G)).
read_all_terms_aux(A,B,C-D,E,F-G):-!,'$__body__'(read_all_terms_aux(A,B,C-D,E,F-G),F=[term_data(A,B)|H]),!,'$__body__'(read_all_terms_aux(A,B,C-D,E,F-G),
			read_all_terms(C-D,E,H-G)).
report_singletons(_,_,[],A-A) :- !.
report_singletons(A,B,C,D-E):-!,'$__body__'(report_singletons(A,B,C,D-E),C=[F=_|G]),!,'$__body__'(report_singletons(A,B,C,D-E),atom_chars(F,H)),!,'$__body__'(report_singletons(A,B,C,D-E),
			report_singletons_aux(H,F,A,B,G,D-E)).
report_singletons_aux(A,B,C,D,E,F-G):-'$__guard__'(report_singletons_aux(A,B,C,D,E,F-G),A=['_'|_]),!,'$__body__'(report_singletons_aux(A,B,C,D,E,F-G),
			report_singletons(C,D,E,F-G)).
report_singletons_aux(A,B,C,D,E,F-G):-!,'$__body__'(report_singletons_aux(A,B,C,D,E,F-G),
			term_string(C,H,[variable_names(D)])),!,'$__body__'(report_singletons_aux(A,B,C,D,E,F-G),
			F = [ format(user_error,'warning: Singleton ~w in ~s.~n',[B,H])
			| I
			]),!,'$__body__'(report_singletons_aux(A,B,C,D,E,F-G),
			report_singletons(C,D,E,I-G)).
A := B :- !,'$__body__'(A:=B,A is B).
iostream(A):-!,'$__body__'(iostream(A),A=[_|_]),!,'$__body__'(iostream(A),iostream_loop(A)).
iostream_loop(A):-'$__guard__'(iostream_loop(A),var(A)),!,'$__body__'(iostream_loop(A),'$__freeze__'(A,iostream_loop(A))).
iostream_loop([A|B]):-'$__guard__'(iostream_loop([A|B]),var(A)),!,'$__body__'(iostream_loop([A|B]),'$__freeze__'(A,iostream_loop([A|B]))).
iostream_loop([]) :- !.
iostream_loop([told]) :- !.
iostream_loop([write(A)|B]):-!,'$__body__'(iostream_loop([write(A)|B]),write(A)),!,'$__body__'(iostream_loop([write(A)|B]),iostream_loop(B)).
iostream_loop([writeln(A)|B]):-!,'$__body__'(iostream_loop([writeln(A)|B]),writeln(A)),!,'$__body__'(iostream_loop([writeln(A)|B]),iostream_loop(B)).
iostream_loop([write_term(A,B)|C]):-!,'$__body__'(iostream_loop([write_term(A,B)|C]),write_term(A,B)),!,'$__body__'(iostream_loop([write_term(A,B)|C]),iostream_loop(C)).
iostream_loop([print_term(A,B)|C]):-!,'$__body__'(iostream_loop([print_term(A,B)|C]),print_term(A,B)),!,'$__body__'(iostream_loop([print_term(A,B)|C]),iostream_loop(C)).
iostream_loop([format(A,B,C)|D]):-!,'$__body__'(iostream_loop([format(A,B,C)|D]),format(A,B,C)),!,'$__body__'(iostream_loop([format(A,B,C)|D]),iostream_loop(D)).
iostream_loop([format(A,B)|C]):-!,'$__body__'(iostream_loop([format(A,B)|C]),format(A,B)),!,'$__body__'(iostream_loop([format(A,B)|C]),iostream_loop(C)).
iostream_loop([nl|A]):-!,'$__body__'(iostream_loop([nl|A]),nl),!,'$__body__'(iostream_loop([nl|A]),iostream_loop(A)).
iostream_loop([ttyflush|A]):-!,'$__body__'(iostream_loop([ttyflush|A]),ttyflush),!,'$__body__'(iostream_loop([ttyflush|A]),iostream_loop(A)).
iostream_loop([flush(A)|B]):-!,'$__body__'(iostream_loop([flush(A)|B]),ttyflush),!,'$__body__'(iostream_loop([flush(A)|B]),A=flushed),!,'$__body__'(iostream_loop([flush(A)|B]),iostream_loop(B)).
iostream_loop([read(A)|B]):-!,'$__body__'(iostream_loop([read(A)|B]),read(A)),!,'$__body__'(iostream_loop([read(A)|B]),iostream_loop(B)).
iostream_loop([open(A,B,C,D)|E]):-!,'$__body__'(iostream_loop([open(A,B,C,D)|E]),open(A,B,C,D)),!,'$__body__'(iostream_loop([open(A,B,C,D)|E]),iostream_loop(E)).
iostream_loop([close(A)|B]):-!,'$__body__'(iostream_loop([close(A)|B]),close(A)),!,'$__body__'(iostream_loop([close(A)|B]),iostream_loop(B)).
iostream_loop([prompt1(A)|B]):-!,'$__body__'(iostream_loop([prompt1(A)|B]),prompt1(A)),!,'$__body__'(iostream_loop([prompt1(A)|B]),iostream_loop(B)).
iostream_loop([read_term(A,B,C)|D]):-!,'$__body__'(iostream_loop([read_term(A,B,C)|D]),read_term(A,B,C)),!,'$__body__'(iostream_loop([read_term(A,B,C)|D]),iostream_loop(D)).
iostream_loop([A|B]):-!,'$__body__'(iostream_loop([A|B]),
			format(user_error,
				   'error: unknown iostream operation: ~w~n',
				   [A])),!,'$__body__'(iostream_loop([A|B]),iostream_loop(B)).
'$__translate__'(A,B):-!,'$__body__'('$__translate__'(A,B),'$__preprocess_dcg__'(A,C)),!,'$__body__'('$__translate__'(A,B),'$__translate_aux__'(C,B)).
'$__translate_aux__'([],[]) :- !.
'$__translate_aux__'([term_data((A:-B|C),D)|E],
					 [term_data((A:-F,!,G),D)|H]):-!,'$__body__'('$__translate_aux__'([term_data((A:-B|C),D)|E],
								 [term_data((A:-F,!,G),D)|H]),
			debug(translate,
				  '~p: ~p',
				  [translate/2,'$__call_guards__'(A,B,F)])),!,'$__body__'('$__translate_aux__'([term_data((A:-B|C),D)|E],
								 [term_data((A:-F,!,G),D)|H]),
			'$__call_guards__'(A,B,F)),!,'$__body__'('$__translate_aux__'([term_data((A:-B|C),D)|E],
								 [term_data((A:-F,!,G),D)|H]),
			debug(translate,
				  '~p: ~p',
				  [translate/2,'$__call_goals__'(A,C,G)])),!,'$__body__'('$__translate_aux__'([term_data((A:-B|C),D)|E],
								 [term_data((A:-F,!,G),D)|H]),
			'$__call_goals__'(A,C,G)),!,'$__body__'('$__translate_aux__'([term_data((A:-B|C),D)|E],
								 [term_data((A:-F,!,G),D)|H]),
			'$__translate_aux__'(E,H)).
'$__translate_aux__'([term_data((A:-B),C)|D],[term_data((A:-!,E),C)|F]):-!,'$__body__'('$__translate_aux__'([term_data((A:-B),C)|D],
								 [term_data((A:-!,E),C)|F]),
			debug(translate,
				  '~p: ~p',
				  [translate/2,'$__call_goals__'(A,B,E)])),!,'$__body__'('$__translate_aux__'([term_data((A:-B),C)|D],
								 [term_data((A:-!,E),C)|F]),
			'$__call_goals__'(A,B,E)),!,'$__body__'('$__translate_aux__'([term_data((A:-B),C)|D],
								 [term_data((A:-!,E),C)|F]),
			'$__translate_aux__'(D,F)).
'$__translate_aux__'([term_data(A,B)|C],[term_data((A:-!),B)|D]):-!,'$__body__'('$__translate_aux__'([term_data(A,B)|C],
								 [term_data((A:-!),B)|D]),
			debug(translate,'~p: ~p',[translate/2,A])),!,'$__body__'('$__translate_aux__'([term_data(A,B)|C],
								 [term_data((A:-!),B)|D]),
			'$__translate_aux__'(C,D)).
'$__call_guards__'(A,(B,C),(D,E)):-!,'$__body__'('$__call_guards__'(A,(B,C),(D,E)),
			'$__call_guards__'(A,B,D)),!,'$__body__'('$__call_guards__'(A,(B,C),(D,E)),
			'$__call_guards__'(A,C,E)).
'$__call_guards__'(A,(B->C),(D->E)):-!,'$__body__'('$__call_guards__'(A,(B->C),(D->E)),
			'$__call_guards__'(A,B,D)),!,'$__body__'('$__call_guards__'(A,(B->C),(D->E)),
			'$__call_guards__'(A,C,E)).
'$__call_guards__'(A,(B;C),(D;E)):-!,'$__body__'('$__call_guards__'(A,(B;C),(D;E)),
			'$__call_guards__'(A,B,D)),!,'$__body__'('$__call_guards__'(A,(B;C),(D;E)),
			'$__call_guards__'(A,C,E)).
'$__call_guards__'(A,true,B):-!,'$__body__'('$__call_guards__'(A,true,B),B=true).
'$__call_guards__'(A,!,B) :- !,'$__body__'('$__call_guards__'(A,!,B),B=!).
'$__call_guards__'(A,var(B),C):-!,'$__body__'('$__call_guards__'(A,var(B),C),C='$__guard__'(A,var(B))).
'$__call_guards__'(A,nonvar(B),C):-!,'$__body__'('$__call_guards__'(A,nonvar(B),C),
			C = '$__guard__'(A,nonvar(B))).
'$__call_guards__'(A,integer(B),C):-!,'$__body__'('$__call_guards__'(A,integer(B),C),
			C = '$__guard__'(A,integer(B))).
'$__call_guards__'(A,B=C,D):-!,'$__body__'('$__call_guards__'(A,B=C,D),D='$__guard__'(A,B=C)).
'$__call_guards__'(A,B=..C,D):-!,'$__body__'('$__call_guards__'(A,B=..C,D),D='$__guard__'(A,B=..C)).
'$__call_guards__'(A,B is C,D):-!,'$__body__'('$__call_guards__'(A,B is C,D),D='$__guard__'(A,B is C)).
'$__call_guards__'(A,B:=C,D):-!,'$__body__'('$__call_guards__'(A,B:=C,D),D='$__guard__'(A,B is C)).
'$__call_guards__'(A,B=\=C,D):-!,'$__body__'('$__call_guards__'(A,B=\=C,D),D='$__guard__'(A,B=\=C)).
'$__call_guards__'(A,B=:=C,D):-!,'$__body__'('$__call_guards__'(A,B=:=C,D),D='$__guard__'(A,B=:=C)).
'$__call_guards__'(A,B<C,D):-!,'$__body__'('$__call_guards__'(A,B<C,D),D='$__guard__'(A,B<C)).
'$__call_guards__'(A,B>C,D):-!,'$__body__'('$__call_guards__'(A,B>C,D),D='$__guard__'(A,B>C)).
'$__call_guards__'(A,B=<C,D):-!,'$__body__'('$__call_guards__'(A,B=<C,D),D='$__guard__'(A,B=<C)).
'$__call_guards__'(A,B>=C,D):-!,'$__body__'('$__call_guards__'(A,B>=C,D),D='$__guard__'(A,B>=C)).
'$__call_guards__'(A,prolog(B),C):-!,'$__body__'('$__call_guards__'(A,prolog(B),C),C='$__guard__'(A,B)).
'$__call_guards__'(A,call(B),C):-!,'$__body__'('$__call_guards__'(A,call(B),C),
			C = '$__guard__'(A,'$__call__'(B))).
'$__call_guards__'(A,freeze(B,C),D):-!,'$__body__'('$__call_guards__'(A,freeze(B,C),D),
			D = '$__guard__'(A,'$__freeze__'(B,C))).
'$__call_guards__'(A,catch(B,C,D),E):-!,'$__body__'('$__call_guards__'(A,catch(B,C,D),E),
			E = '$__guard__'(A,'$__catch__'(B,C,D))).
'$__call_guards__'(A,abolish(B,C),D):-!,'$__body__'('$__call_guards__'(A,abolish(B,C),D),
			D = '$__guard__'(A,'$__abolish__'(B,C))).
'$__call_guards__'(A,asserta(B),C):-!,'$__body__'('$__call_guards__'(A,asserta(B),C),
			C = '$__guard__'(A,'$__asserta__'(B))).
'$__call_guards__'(A,assertz(B),C):-!,'$__body__'('$__call_guards__'(A,assertz(B),C),
			C = '$__guard__'(A,'$__assertz__'(B))).
'$__call_guards__'(A,B,C):-!,'$__body__'('$__call_guards__'(A,B,C),C='$__guard__'(A,B)).
'$__call_goals__'(A,(B,C),(D,!,E)):-!,'$__body__'('$__call_goals__'(A,(B,C),(D,!,E)),
			debug(translate,
				  '~p: ~p',
				  ['$__call_goals__'/3,'$__call_goals__'(A,B,D)])),!,'$__body__'('$__call_goals__'(A,(B,C),(D,!,E)),
			'$__call_goals__'(A,B,D)),!,'$__body__'('$__call_goals__'(A,(B,C),(D,!,E)),
			debug(translate,
				  '~p: ~p',
				  ['$__call_goals__'/3,'$__call_goals__'(A,C,E)])),!,'$__body__'('$__call_goals__'(A,(B,C),(D,!,E)),
			'$__call_goals__'(A,C,E)).
'$__call_goals__'(A,(B->C),D):-!,'$__body__'('$__call_goals__'(A,(B->C),D),functor(A,E,F)),!,'$__body__'('$__call_goals__'(A,(B->C),D),
			throw(error(crash(E/F,compile,'"->" not allowed in body'),
						context(A)))).
'$__call_goals__'(A,(B;C),D):-!,'$__body__'('$__call_goals__'(A,(B;C),D),functor(A,E,F)),!,'$__body__'('$__call_goals__'(A,(B;C),D),
			throw(error(crash(E/F,compile,'";" not allowed in body'),
						context(A)))).
'$__call_goals__'(A,!,B):-!,'$__body__'('$__call_goals__'(A,!,B),functor(A,C,D)),!,'$__body__'('$__call_goals__'(A,!,B),
			throw(error(crash(C/D,compile,'"!" not allowed in body'),
						context(A)))).
'$__call_goals__'(_,true,true) :- !.
'$__call_goals__'(A,B=C,D):-!,'$__body__'('$__call_goals__'(A,B=C,D),D='$__body__'(A,B=C)).
'$__call_goals__'(A,B:=C,D):-!,'$__body__'('$__call_goals__'(A,B:=C,D),D='$__body__'(A,B is C)).
'$__call_goals__'(A,B is C,D):-!,'$__body__'('$__call_goals__'(A,B is C,D),D='$__body__'(A,B is C)).
'$__call_goals__'(A,B=..C,D):-!,'$__body__'('$__call_goals__'(A,B=..C,D),D='$__body__'(A,B=..C)).
'$__call_goals__'(A,prolog(B),C):-!,'$__body__'('$__call_goals__'(A,prolog(B),C),C='$__body__'(A,B)).
'$__call_goals__'(A,call(B),C):-!,'$__body__'('$__call_goals__'(A,call(B),C),
			C = '$__body__'(A,'$__call__'(B))).
'$__call_goals__'(A,freeze(B,C),D):-!,'$__body__'('$__call_goals__'(A,freeze(B,C),D),
			D = '$__body__'(A,'$__freeze__'(B,C))).
'$__call_goals__'(A,catch(B,C,D),E):-!,'$__body__'('$__call_goals__'(A,catch(B,C,D),E),
			E = '$__body__'(A,'$__catch__'(B,C,D))).
'$__call_goals__'(A,abolish(B,C),D):-!,'$__body__'('$__call_goals__'(A,abolish(B,C),D),
			D = '$__body__'(A,'$__abolish__'(B,C))).
'$__call_goals__'(A,asserta(B),C):-!,'$__body__'('$__call_goals__'(A,asserta(B),C),
			C = '$__body__'(A,'$__asserta__'(B))).
'$__call_goals__'(A,assertz(B),C):-!,'$__body__'('$__call_goals__'(A,assertz(B),C),
			C = '$__body__'(A,'$__assertz__'(B))).
'$__call_goals__'(A,B,C):-!,'$__body__'('$__call_goals__'(A,B,C),C='$__body__'(A,B)).
'$__rename__'(call(A),B):-!,'$__body__'('$__rename__'(call(A),B),'$__call_goals__'(call(A),A,B)).
'$__rename__'(freeze(A,B),C):-!,'$__body__'('$__rename__'(freeze(A,B),C),
			'$__call_goals__'(freeze(B),B,D)),!,'$__body__'('$__rename__'(freeze(A,B),C),C=freeze(A,D)).
'$__rename__'(catch(A,B,C),D):-!,'$__body__'('$__rename__'(catch(A,B,C),D),
			'$__call_goals__'(freeze(A),A,E)),!,'$__body__'('$__rename__'(catch(A,B,C),D),
			'$__call_goals__'(freeze(C),A,F)),!,'$__body__'('$__rename__'(catch(A,B,C),D),D=catch(E,B,F)).
'$__rename__'(prolog(A),B):-!,'$__body__'('$__rename__'(prolog(A),B),B=A).
'$__rename__'(A,A) :- !.
'$__call__'(A):-!,'$__body__'('$__call__'(A),'$__rename__'(A,B)),!,'$__body__'('$__call__'(A),debug(translate,'~p: ~p',[call/1,call(B)])),!,'$__body__'('$__call__'(A),call(B)).
'$__freeze__'(A,B):-!,'$__body__'('$__freeze__'(A,B),
			debug(translate,'~p: ~p',[freeze/1,freeze(A,B)])),!,'$__body__'('$__freeze__'(A,B),
			freeze(A,('$__rename__'(B,C),'$__call__'(C)))).
'$__catch__'(A,B,C):-!,'$__body__'('$__catch__'(A,B,C),
			debug(translate,'~p: ~p',[catch/1,catch(A,B,C)])),!,'$__body__'('$__catch__'(A,B,C),
			catch(('$__rename__'(A,D),'$__call__'(D)),
				  B,
				  ('$__rename__'(C,E),'$__call__'(E)))).
'$__abolish__'(A,B):-!,'$__body__'('$__abolish__'(A,B),
			debug(translate,'~p: ~p',[abolish/1,A/B])),!,'$__body__'('$__abolish__'(A,B),abolish(A,B)).
'$__asserta__'(A):-!,'$__body__'('$__asserta__'(A),
			'$__translate__'([term_data(A,[])],[term_data(B,_)])),!,'$__body__'('$__asserta__'(A),debug(translate,'~p: ~p',[asserta/1,B])),!,'$__body__'('$__asserta__'(A),asserta(B)).
'$__assertz__'(A):-!,'$__body__'('$__assertz__'(A),
			'$__translate__'([term_data(A,[])],[term_data(B,_)])),!,'$__body__'('$__assertz__'(A),debug(translate,'~p: ~p',[assertz/1,B])),!,'$__body__'('$__assertz__'(A),assertz(B)).
'$__preprocess_dcg__'([],[]) :- !.
'$__preprocess_dcg__'([term_data(A,B)|C],[term_data(D,B)|E]):-!,'$__body__'('$__preprocess_dcg__'([term_data(A,B)|C],
								  [term_data(D,B)|E]),
			'$__preprocess_dcg_term__'(A,D)),!,'$__body__'('$__preprocess_dcg__'([term_data(A,B)|C],
								  [term_data(D,B)|E]),
			'$__preprocess_dcg__'(C,E)).
'$__preprocess_dcg_term__'((A-->B|C),D):-( '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),D),E=(A-->B|C)),
  '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),D),
			   '$__may_be_stream__'(B)),
  '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),D),
			   '$__may_be_stream__'(C))
),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),D),
			throw(error(invalid_predicate(E)))).
'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)):-( '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   G=(A --> B'|'C)),
  '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   '$__may_be_stream__'(B))
),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			'$__preprocess_dcg_stream__'(G,B,H-I,E)),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),A=..[J|K]),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			append(K,[H,I],L)),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),D=..[J|L]),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),F=C).
'$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)):-( '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   G=(A --> B'|'C)),
  '$__guard__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			   '$__may_be_stream__'(C))
),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			'$__preprocess_dcg_stream__'(G,C,H-I,F)),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),A=..[J|K]),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),
			append(K,[H,I],L)),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),D=..[J|L]),!,'$__body__'('$__preprocess_dcg_term__'((A-->B|C),(D:-E|F)),E=B).
'$__preprocess_dcg_term__'((A-->B),(C:-D)):-( '$__guard__'('$__preprocess_dcg_term__'((A-->B),(C:-D)),E=(A-->B)),
  '$__guard__'('$__preprocess_dcg_term__'((A-->B),(C:-D)),
			   '$__may_be_stream__'(B))
),!,'$__body__'('$__preprocess_dcg_term__'((A-->B),(C:-D)),
			'$__preprocess_dcg_stream__'(E,B,F-G,D)),!,'$__body__'('$__preprocess_dcg_term__'((A-->B),(C:-D)),A=..[H|I]),!,'$__body__'('$__preprocess_dcg_term__'((A-->B),(C:-D)),
			append(I,[F,G],J)),!,'$__body__'('$__preprocess_dcg_term__'((A-->B),(C:-D)),C=..[H|J]).
'$__preprocess_dcg_term__'(A,A) :- !.
'$__may_be_stream__'(A):-( '$__guard__'('$__may_be_stream__'(A),'$__may_be_stream__'(A,false,B)),
  '$__guard__'('$__may_be_stream__'(A),B=true)
),!,true.
'$__may_be_stream__'(({A},B),C,D):-!,'$__body__'('$__may_be_stream__'(({A},B),C,D),D=true).
'$__may_be_stream__'(([],A),B,C):-!,'$__body__'('$__may_be_stream__'(([],A),B,C),C=true).
'$__may_be_stream__'(([A|B],C),D,E):-!,'$__body__'('$__may_be_stream__'(([A|B],C),D,E),E=true).
'$__may_be_stream__'((A,B),C,D):-!,'$__body__'('$__may_be_stream__'((A,B),C,D),
			'$__may_be_stream__'(B,C,D)).
'$__may_be_stream__'({A},B,C):-!,'$__body__'('$__may_be_stream__'({A},B,C),C=true).
'$__may_be_stream__'([],A,B):-!,'$__body__'('$__may_be_stream__'([],A,B),B=true).
'$__may_be_stream__'([A|B],C,D):-!,'$__body__'('$__may_be_stream__'([A|B],C,D),D=true).
'$__may_be_stream__'(A,B,C):-!,'$__body__'('$__may_be_stream__'(A,B,C),C=B).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,F):-'$__guard__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,F),B=[]),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,F),
			'$__preprocess_dcg_stream__'(A,C,D-E,F)).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)):-'$__guard__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),B=[_|_]),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__extend_list__'(B,H-I)),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),F=(D=H)),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__preprocess_dcg_stream__'(A,C,I-E,G)).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)):-'$__guard__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),B={H}),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),F=H),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__preprocess_dcg_stream__'(A,C,D-E,G)).
'$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)):-'$__guard__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),B=..[H|I]),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			append(I,[D,J],K)),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),F=..[H|K]),!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D-E,(F,G)),
			'$__preprocess_dcg_stream__'(A,C,J-E,G)).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('$__preprocess_dcg_stream__'(A,B,C-D,E),B=[]),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),E=(C=D)).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('$__preprocess_dcg_stream__'(A,B,C-D,E),B=[_|_]),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),
			'$__extend_list__'(B,F-D)),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),E=(C=F)).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('$__preprocess_dcg_stream__'(A,B,C-D,E),B={F}),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),E=F),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),C=D).
'$__preprocess_dcg_stream__'(A,B,C-D,E):-'$__guard__'('$__preprocess_dcg_stream__'(A,B,C-D,E),B=..[F|G]),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),append(G,[C,D],H)),!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C-D,E),E=..[F|H]).
'$__preprocess_dcg_stream__'(A,(B,C),D,E):-!,'$__body__'('$__preprocess_dcg_stream__'(A,(B,C),D,E),
			throw(error(invalid_predicate(A,B)))).
'$__preprocess_dcg_stream__'(A,B,C,D):-!,'$__body__'('$__preprocess_dcg_stream__'(A,B,C,D),
			throw(error(invalid_predicate(A,B)))).
'$__extend_list__'([],A-A) :- !.
'$__extend_list__'([A|B],C-D):-!,'$__body__'('$__extend_list__'([A|B],C-D),C=[A|E]),!,'$__body__'('$__extend_list__'([A|B],C-D),'$__extend_list__'(B,E-D)).
