#!/usr/bin/env swipl
% This code is generated by MLP compiler
% source: [src/mlpc.mlp,builtin.mlp,src/mlpc_runtime.mlp,src/mlpc_preprocess.mlp]
:- initialization('$_main', main).
% main wrapper
'$_main' :-
    current_prolog_flag(argv, Argv),
    g__main(['src/mlpc.mlp'|Argv]).
% runtime predicates
% call wrapper
m__rename__('=', '=').
m__rename__(Name, Name2) :-
    atom_concat('g__', Name, Name2).
m__rename_term__(Term, Term2) :-
    Term =.. [F|Args],
    m__rename__(F, F2),
    Term2 =.. [F2|Args].
m__call__(Goal) :- 
    g__call_goals(call(Goal), Goal, RealGoal),
    call(RealGoal).
m__guard__(Head, RealGoal) :- 
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, guard, RealGoal)])
    ; debug(mlpc, '~p', [fail(Name/Arity, guard, RealGoal)]), !, fail ).
m__guard__(Head, DispGoal, RealGoal) :- 
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, guard, DispGoal)])
    ; debug(mlpc, '~p', [fail(Name/Arity, guard, RealGoal)]), !, fail ).
m__body__(Head, RealGoal) :-
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, body, RealGoal)])
    ; throw(error(crash(Name/Arity, RealGoal),
                  context(Head, RealGoal))) ).
m__body__(Head, DispGoal, RealGoal) :-
    functor(Head, Name, Arity),
    ( call(RealGoal) -> debug(mlpc, '~p', [success(Name/Arity, body, DispGoal)])
    ; throw(error(crash(Name/Arity, DispGoal),
            context(Head, DispGoal))) ).
m__freeze__(Head, X, G) :-
    functor(Head, Name, Arity),
    ( freeze(X, m__call__(G)) -> debug(mlpc, '~p', [success(Name/Arity, freeze(X, G))])
    ; throw(error(crash(Name/Arity, freeze(X, G)),
                  context(Head, freeze(X, G)))) ).
m__catch__(G, Error, Recover) :-
    catch(m__call__(G), Error, m__call__(Recover)).
m__abolish__(Name, Arity) :-
    m__rename__(Name, Name2),
    abolish(Name2, Arity).
m__asserta__(Term) :-
    g__translate([term_data(Term, [])], [term_data(Term2, _)]),
    asserta(Term2).
m__assertz__(Term) :-
    g__translate([term_data(Term, [])], [term_data(Term2, _)]),
    assertz(Term2).
% generated source codes
% generated source codes
g__main([A|B]):-m__body__(main([A|B]),g__debug(main,':~p',[parse_args])),!,m__body__(main([A|B]),g__parse_args(B,C,D-[])),!,m__body__(main([A|B]),g__append_runtime_sources(C,E)),!,m__body__(main([A|B]),g__load_term_data(E,F-[])),!,m__body__(main([A|B]),g__preprocess_dcg(F,G)),!,m__body__(main([A|B]),g__debug(main,':~p',[translate])),!,m__body__(main([A|B]),g__translate(G,H)),!,m__body__(main([A|B]),g__debug(main,':~p',[write_file_header])),!,m__body__(main([A|B]),g__iostream(I)),!,m__body__(main([A|B]),g__write_file_header(E,D,I-J)),!,m__body__(main([A|B]),g__debug(main,':~p',[write_term_data])),!,m__body__(main([A|B]),g__write_term_data(H,J)).
g__append_runtime_sources([],A):-m__body__(append_runtime_sources([],A),
		  A=['src/mlpc_runtime.mlp','src/mlpc_preprocess.mlp']).
g__append_runtime_sources([A|B],C):-m__guard__(append_runtime_sources([A|B],C),A='src/mlpc_runtime.mlp'),!,m__body__(append_runtime_sources([A|B],C),
		  g__append_runtime_sources(B,C)).
g__append_runtime_sources([A|B],C):-m__guard__(append_runtime_sources([A|B],C),A='src/mlpc_preprocess.mlp'),!,m__body__(append_runtime_sources([A|B],C),
		  g__append_runtime_sources(B,C)).
g__append_runtime_sources([A|B],C):-m__body__(append_runtime_sources([A|B],C),C=[A|D]),!,m__body__(append_runtime_sources([A|B],C),
		  g__append_runtime_sources(B,D)).
g__parse_args(A,B,C-D):-m__body__(parse_args(A,B,C-D),g__phrase(opt_parse_dcg(B,C-D),A,[])).
g__opt_parse_dcg([],A-A,B,C):-m__guard__(opt_parse_dcg([],A-A,B,C),B=['-h'|C]),!,m__body__(opt_parse_dcg([],A-A,B,C),
		  g__iostream([writeln('usage: mlpc_opt <SourceFile..>'),told])).
g__opt_parse_dcg(A,[debug|B]-C,D,E):-( m__guard__(opt_parse_dcg(A,[debug|B]-C,D,E),D=['-d'|F]),
  m__guard__(opt_parse_dcg(A,[debug|B]-C,D,E),
			 g__opt_parse_dcg(A,B-C,F,E))
),!,true.
g__opt_parse_dcg([A|B],C-D,E,F):-( m__guard__(opt_parse_dcg([A|B],C-D,E,F),E=[A|G]),
  m__guard__(opt_parse_dcg([A|B],C-D,E,F),g__opt_parse_dcg(B,C-D,G,F))
),!,true.
g__opt_parse_dcg([],A-A,B,C):-m__guard__(opt_parse_dcg([],A-A,B,C),B=C),!,true.
g__write_file_header(A,B,C-D):-m__body__(write_file_header(A,B,C-D),A=[E|_]),!,m__body__(write_file_header(A,B,C-D),
		  C = [ writeln('#!/usr/bin/env swipl'),
			writeln('% This code is generated by MLP compiler'),
			format('% source: ~w~n',[A]),
			writeln(':- initialization(\'$_main\', main).'),
			writeln('% main wrapper'),
			writeln('\'$_main\' :-')
		  | F
		  ]),!,m__body__(write_file_header(A,B,C-D),g__append_debug(B,F-G)),!,m__body__(write_file_header(A,B,C-D),
		  G = [ writeln('    current_prolog_flag(argv, Argv),'),
			format('    g__main([\'~s\'|Argv]).~n',E),
			writeln('% runtime predicates'),
			writeln('% call wrapper'),
			writeln('m__rename__(\'=\', \'=\').'),
			writeln('m__rename__(Name, Name2) :-'),
			writeln('    atom_concat(\'g__\', Name, Name2).'),
			writeln('m__rename_term__(Term, Term2) :-'),
			writeln('    Term =.. [F|Args],'),
			writeln('    m__rename__(F, F2),'),
			writeln('    Term2 =.. [F2|Args].'),
			writeln('m__call__(Goal) :- '),
			writeln('    g__call_goals(call(Goal), Goal, RealGoal),'),
			writeln('    call(RealGoal).'),
			writeln('m__guard__(Head, RealGoal) :- '),
			writeln('    functor(Head, Name, Arity),'),
			writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, guard, RealGoal)])'),
			writeln('    ; debug(mlpc, \'~p\', [fail(Name/Arity, guard, RealGoal)]), !, fail ).'),
			writeln('m__guard__(Head, DispGoal, RealGoal) :- '),
			writeln('    functor(Head, Name, Arity),'),
			writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, guard, DispGoal)])'),
			writeln('    ; debug(mlpc, \'~p\', [fail(Name/Arity, guard, RealGoal)]), !, fail ).'),
			writeln('m__body__(Head, RealGoal) :-'),
			writeln('    functor(Head, Name, Arity),'),
			writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, body, RealGoal)])'),
			writeln('    ; throw(error(crash(Name/Arity, RealGoal),'),
			writeln('                  context(Head, RealGoal))) ).'),
			writeln('m__body__(Head, DispGoal, RealGoal) :-'),
			writeln('    functor(Head, Name, Arity),'),
			writeln('    ( call(RealGoal) -> debug(mlpc, \'~p\', [success(Name/Arity, body, DispGoal)])'),
			writeln('    ; throw(error(crash(Name/Arity, DispGoal),'),
			writeln('            context(Head, DispGoal))) ).'),
			writeln('m__freeze__(Head, X, G) :-'),
			writeln('    functor(Head, Name, Arity),'),
			writeln('    ( freeze(X, m__call__(G)) -> debug(mlpc, \'~p\', [success(Name/Arity, freeze(X, G))])'),
			writeln('    ; throw(error(crash(Name/Arity, freeze(X, G)),'),
			writeln('                  context(Head, freeze(X, G)))) ).'),
			writeln('m__catch__(G, Error, Recover) :-'),
			writeln('    catch(m__call__(G), Error, m__call__(Recover)).'),
			writeln('m__abolish__(Name, Arity) :-'),
			writeln('    m__rename__(Name, Name2),'),
			writeln('    abolish(Name2, Arity).'),
			writeln('m__asserta__(Term) :-'),
			writeln('    g__translate([term_data(Term, [])], [term_data(Term2, _)]),'),
			writeln('    asserta(Term2).'),
			writeln('m__assertz__(Term) :-'),
			writeln('    g__translate([term_data(Term, [])], [term_data(Term2, _)]),'),
			writeln('    assertz(Term2).'),
			writeln('% generated source codes'),
			writeln('% generated source codes')
		  | D
		  ]).
g__append_debug([debug|A],B-C):-m__body__(append_debug([debug|A],B-C),
		  B=[writeln('    debug(mlpc),')|C]).
g__append_debug(A,B-C) :- m__body__(append_debug(A,B-C),B=C).
g__write_term_data([],A) :- m__body__(write_term_data([],A),A=[told]).
g__write_term_data([A|B],C):-m__guard__(write_term_data([A|B],C),A=term_data(D,E)),!,m__body__(write_term_data([A|B],C),
		  C = [ print_term(D,[variable_names(E),tab_width(4)]),
			writeln('.')
		  | F
		  ]),!,m__body__(write_term_data([A|B],C),g__write_term_data(B,F)).
g__load_term_data([],A-A).
g__load_term_data([A|B],C-D):-m__body__(load_term_data([A|B],C-D),g__iostream(E)),!,m__body__(load_term_data([A|B],C-D),
		  E=[open(A,read,F,[encoding(utf8)])|G]),!,m__body__(load_term_data([A|B],C-D),g__read_all_terms(G-H,F,C-I)),!,m__body__(load_term_data([A|B],C-D),H=[close(F),told]),!,m__body__(load_term_data([A|B],C-D),g__load_term_data(B,I-D)).
g__read_all_terms(A-B,C,D-E):-m__body__(read_all_terms(A-B,C,D-E),
		  A = [ read_term(C,
					  F,
					  [ variable_names(G),
						singletons(H),
						syntax_errors(dec10)
					  ])
		  | I
		  ]),!,m__body__(read_all_terms(A-B,C,D-E),g__report_singletons(F,G,H,I-J)),!,m__body__(read_all_terms(A-B,C,D-E),
		  g__read_all_terms_aux(F,G,J-B,C,D-E)).
g__read_all_terms_aux(A,B,C-D,E,F-G):-m__guard__(read_all_terms_aux(A,B,C-D,E,F-G),A=end_of_file),!,m__body__(read_all_terms_aux(A,B,C-D,E,F-G),C=D),!,m__body__(read_all_terms_aux(A,B,C-D,E,F-G),F=G).
g__read_all_terms_aux(A,B,C-D,E,F-G):-m__guard__(read_all_terms_aux(A,B,C-D,E,F-G),A=otherwise),!,m__body__(read_all_terms_aux(A,B,C-D,E,F-G),
		  g__read_all_terms(C-D,E,F-G)).
g__read_all_terms_aux(A,B,C-D,E,F-G):-m__body__(read_all_terms_aux(A,B,C-D,E,F-G),
		  g__preprocess_dcg_term(A,H)),!,m__body__(read_all_terms_aux(A,B,C-D,E,F-G),F=[term_data(H,B)|I]),!,m__body__(read_all_terms_aux(A,B,C-D,E,F-G),
		  g__read_all_terms(C-D,E,I-G)).
g__report_singletons(_,_,[],A-A).
g__report_singletons(A,B,C,D-E):-m__body__(report_singletons(A,B,C,D-E),C=[F=_|G]),!,m__body__(report_singletons(A,B,C,D-E),g__atom_chars(F,H)),!,m__body__(report_singletons(A,B,C,D-E),
		  g__report_singletons_aux(H,F,A,B,G,D-E)).
g__report_singletons_aux(A,B,C,D,E,F-G):-m__guard__(report_singletons_aux(A,B,C,D,E,F-G),A=['_'|_]),!,m__body__(report_singletons_aux(A,B,C,D,E,F-G),
		  g__report_singletons(C,D,E,F-G)).
g__report_singletons_aux(A,B,C,D,E,F-G):-m__body__(report_singletons_aux(A,B,C,D,E,F-G),
		  g__term_string(C,H,[variable_names(D)])),!,m__body__(report_singletons_aux(A,B,C,D,E,F-G),
		  F = [format(user_error,'warning: Singleton ~w in ~s.~n',[B,H])|I]),!,m__body__(report_singletons_aux(A,B,C,D,E,F-G),
		  g__report_singletons(C,D,E,I-G)).
'g__:='(A,B) :- m__body__(A:=B,A is B).
g__term_to_atom(A,B):-m__guard__(term_to_atom(A,B),term_to_atom(A,B)),!,true.
g__atom_chars(A,B) :- m__guard__(atom_chars(A,B),atom_chars(A,B)),!,true.
g__atom_concat(A,B,C):-m__guard__(atom_concat(A,B,C),atom_concat(A,B,C)),!,true.
g__atom_number(A,B):-m__guard__(atom_number(A,B),atom_number(A,B)),!,true.
g__term_string(A,B,C):-m__guard__(term_string(A,B,C),term_string(A,B,C)),!,true.
g__functor(A,B,C) :- m__guard__(functor(A,B,C),functor(A,B,C)),!,true.
g__phrase(A,B,C):-m__body__(phrase(A,B,C),A=..[D|E]),!,m__body__(phrase(A,B,C),g__append(E,[B,C],F)),!,m__body__(phrase(A,B,C),G=..[D|F]),!,m__body__(phrase(A,B,C),m__call__(G)).
g__append(A,B,C) :- m__guard__(append(A,B,C),append(A,B,C)),!,true.
g__debug(A) :- m__guard__(debug(A),debug(A)),!,true.
g__nodebug(A) :- m__guard__(nodebug(A),nodebug(A)),!,true.
g__debug(A,B,C) :- m__guard__(debug(A,B,C),debug(A,B,C)),!,true.
g__write(A) :- m__guard__(write(A),write(A)),!,true.
g__writeln(A) :- m__guard__(writeln(A),writeln(A)),!,true.
g__nl :- m__guard__(nl,nl),!,true.
g__write(A,B) :- m__guard__(write(A,B),write(A,B)),!,true.
g__writeln(A,B) :- m__guard__(writeln(A,B),writeln(A,B)),!,true.
g__nl(A) :- m__guard__(nl(A),nl(A)),!,true.
g__iostream(A):-m__body__(iostream(A),A=[_|_]),!,m__body__(iostream(A),g__iostream_loop(A)).
g__iostream_loop(A):-m__guard__(iostream_loop(A),var(A)),!,m__body__(iostream_loop(A),
		  m__freeze__(iostream_loop(A),A,iostream_loop(A))).
g__iostream_loop([A|B]):-m__guard__(iostream_loop([A|B]),var(A)),!,m__body__(iostream_loop([A|B]),
		  m__freeze__(iostream_loop([A|B]),A,iostream_loop([A|B]))).
g__iostream_loop([]).
g__iostream_loop([told]).
g__iostream_loop([write(A)|B]):-m__body__(iostream_loop([write(A)|B]),write(A)),!,m__body__(iostream_loop([write(A)|B]),g__iostream_loop(B)).
g__iostream_loop([writeln(A)|B]):-m__body__(iostream_loop([writeln(A)|B]),writeln(A)),!,m__body__(iostream_loop([writeln(A)|B]),g__iostream_loop(B)).
g__iostream_loop([write_term(A,B)|C]):-m__body__(iostream_loop([write_term(A,B)|C]),write_term(A,B)),!,m__body__(iostream_loop([write_term(A,B)|C]),g__iostream_loop(C)).
g__iostream_loop([print_term(A,B)|C]):-m__body__(iostream_loop([print_term(A,B)|C]),print_term(A,B)),!,m__body__(iostream_loop([print_term(A,B)|C]),g__iostream_loop(C)).
g__iostream_loop([format(A,B,C)|D]):-m__body__(iostream_loop([format(A,B,C)|D]),format(A,B,C)),!,m__body__(iostream_loop([format(A,B,C)|D]),g__iostream_loop(D)).
g__iostream_loop([format(A,B)|C]):-m__body__(iostream_loop([format(A,B)|C]),format(A,B)),!,m__body__(iostream_loop([format(A,B)|C]),g__iostream_loop(C)).
g__iostream_loop([nl|A]):-m__body__(iostream_loop([nl|A]),nl),!,m__body__(iostream_loop([nl|A]),g__iostream_loop(A)).
g__iostream_loop([ttyflush|A]):-m__body__(iostream_loop([ttyflush|A]),ttyflush),!,m__body__(iostream_loop([ttyflush|A]),g__iostream_loop(A)).
g__iostream_loop([flush(A)|B]):-m__body__(iostream_loop([flush(A)|B]),ttyflush),!,m__body__(iostream_loop([flush(A)|B]),A=flushed),!,m__body__(iostream_loop([flush(A)|B]),g__iostream_loop(B)).
g__iostream_loop([read(A)|B]):-m__body__(iostream_loop([read(A)|B]),read(A)),!,m__body__(iostream_loop([read(A)|B]),g__iostream_loop(B)).
g__iostream_loop([open(A,B,C,D)|E]):-m__body__(iostream_loop([open(A,B,C,D)|E]),open(A,B,C,D)),!,m__body__(iostream_loop([open(A,B,C,D)|E]),g__iostream_loop(E)).
g__iostream_loop([close(A)|B]):-m__body__(iostream_loop([close(A)|B]),close(A)),!,m__body__(iostream_loop([close(A)|B]),g__iostream_loop(B)).
g__iostream_loop([prompt1(A)|B]):-m__body__(iostream_loop([prompt1(A)|B]),prompt1(A)),!,m__body__(iostream_loop([prompt1(A)|B]),g__iostream_loop(B)).
g__iostream_loop([read_term(A,B,C)|D]):-m__body__(iostream_loop([read_term(A,B,C)|D]),read_term(A,B,C)),!,m__body__(iostream_loop([read_term(A,B,C)|D]),g__iostream_loop(D)).
g__iostream_loop([A|B]):-m__body__(iostream_loop([A|B]),
		  format(user_error,
				 'error: unknown iostream operation: ~w~n',
				 [A])),!,m__body__(iostream_loop([A|B]),g__iostream_loop(B)).
g__translate([],[]).
g__translate([term_data((A:-B|C),D)|E],[term_data((F:-G,!,H),D)|I]):-m__body__(translate([term_data((A:-B|C),D)|E],
					[term_data((F:-G,!,H),D)|I]),
		  g__debug(translate,':~p ~p',[translate1,call_guards(A,B,G)])),!,m__body__(translate([term_data((A:-B|C),D)|E],
					[term_data((F:-G,!,H),D)|I]),
		  g__call_guards(A,B,G)),!,m__body__(translate([term_data((A:-B|C),D)|E],
					[term_data((F:-G,!,H),D)|I]),
		  g__debug(translate,':~p ~p',[translate1,call_goals(A,C,H)])),!,m__body__(translate([term_data((A:-B|C),D)|E],
					[term_data((F:-G,!,H),D)|I]),
		  g__call_goals(A,C,H)),!,m__body__(translate([term_data((A:-B|C),D)|E],
					[term_data((F:-G,!,H),D)|I]),
		  g__rename_term(A,F)),!,m__body__(translate([term_data((A:-B|C),D)|E],
					[term_data((F:-G,!,H),D)|I]),
		  g__translate(E,I)).
g__translate([term_data((A:-B),C)|D],[term_data((E:-F),C)|G]):-m__body__(translate([term_data((A:-B),C)|D],[term_data((E:-F),C)|G]),
		  g__rename_term(A,E)),!,m__body__(translate([term_data((A:-B),C)|D],[term_data((E:-F),C)|G]),
		  g__debug(translate,':~p ~p',[translate2,call_goals(A,B,F)])),!,m__body__(translate([term_data((A:-B),C)|D],[term_data((E:-F),C)|G]),
		  g__call_goals(A,B,F)),!,m__body__(translate([term_data((A:-B),C)|D],[term_data((E:-F),C)|G]),
		  g__translate(D,G)).
g__translate([term_data(A,B)|C],[term_data(D,B)|E]):-m__body__(translate([term_data(A,B)|C],[term_data(D,B)|E]),
		  g__debug(translate,':~p ~p',[translate3,A])),!,m__body__(translate([term_data(A,B)|C],[term_data(D,B)|E]),
		  g__rename_term(A,D)),!,m__body__(translate([term_data(A,B)|C],[term_data(D,B)|E]),
		  g__translate(C,E)).
g__call_guards(A,(B,C),(D,E)):-m__body__(call_guards(A,(B,C),(D,E)),g__call_guards(A,B,D)),!,m__body__(call_guards(A,(B,C),(D,E)),g__call_guards(A,C,E)).
g__call_guards(A,true,B) :- m__body__(call_guards(A,true,B),B=true).
g__call_guards(A,var(B),C):-m__body__(call_guards(A,var(B),C),C=m__guard__(A,var(B))).
g__call_guards(A,nonvar(B),C):-m__body__(call_guards(A,nonvar(B),C),C=m__guard__(A,nonvar(B))).
g__call_guards(A,integer(B),C):-m__body__(call_guards(A,integer(B),C),C=m__guard__(A,integer(B))).
g__call_guards(A,B=C,D):-m__body__(call_guards(A,B=C,D),D=m__guard__(A,B=C)).
g__call_guards(A,B=..C,D):-m__body__(call_guards(A,B=..C,D),D=m__guard__(A,B=..C)).
g__call_guards(A,B is C,D):-m__body__(call_guards(A,B is C,D),D=m__guard__(A,B is C)).
g__call_guards(A,B:=C,D):-m__body__(call_guards(A,B:=C,D),D=m__guard__(A,B is C)).
g__call_guards(A,B=\=C,D):-m__body__(call_guards(A,B=\=C,D),D=m__guard__(A,B=\=C)).
g__call_guards(A,B=:=C,D):-m__body__(call_guards(A,B=:=C,D),D=m__guard__(A,B=:=C)).
g__call_guards(A,B<C,D):-m__body__(call_guards(A,B<C,D),D=m__guard__(A,B<C)).
g__call_guards(A,B>C,D):-m__body__(call_guards(A,B>C,D),D=m__guard__(A,B>C)).
g__call_guards(A,B=<C,D):-m__body__(call_guards(A,B=<C,D),D=m__guard__(A,B=<C)).
g__call_guards(A,B>=C,D):-m__body__(call_guards(A,B>=C,D),D=m__guard__(A,B>=C)).
g__call_guards(A,prolog(B),C):-m__body__(call_guards(A,prolog(B),C),C=m__guard__(A,B)).
g__call_guards(A,call(B),C):-m__body__(call_guards(A,call(B),C),C=m__guard__(A,m__call__(B))).
g__call_guards(A,freeze(B,C),D):-m__body__(call_guards(A,freeze(B,C),D),
		  D=m__guard__(A,m__freeze__(B,C))).
g__call_guards(A,catch(B,C,D),E):-m__body__(call_guards(A,catch(B,C,D),E),
		  E=m__guard__(A,m__catch__(B,C,D))).
g__call_guards(A,abolish(B,C),D):-m__body__(call_guards(A,abolish(B,C),D),
		  D=m__guard__(A,m__abolish__(B,C))).
g__call_guards(A,asserta(B),C):-m__body__(call_guards(A,asserta(B),C),C=m__guard__(A,m__asserta__(B))).
g__call_guards(A,assertz(B),C):-m__body__(call_guards(A,assertz(B),C),C=m__guard__(A,m__assertz__(B))).
g__call_guards(A,B,C):-m__body__(call_guards(A,B,C),g__rename_term(B,D)),!,m__body__(call_guards(A,B,C),C=m__guard__(A,D)).
g__call_goals(A,(B,C),(D,!,E)):-m__body__(call_goals(A,(B,C),(D,!,E)),
		  g__debug(translate,':~p ~p',[call_goals1,call_goals(A,B,D)])),!,m__body__(call_goals(A,(B,C),(D,!,E)),g__call_goals(A,B,D)),!,m__body__(call_goals(A,(B,C),(D,!,E)),
		  g__debug(translate,':~p ~p',[call_goals2,call_goals(A,C,E)])),!,m__body__(call_goals(A,(B,C),(D,!,E)),g__call_goals(A,C,E)).
g__call_goals(_,true,true).
g__call_goals(A,B=C,D):-m__body__(call_goals(A,B=C,D),D=m__body__(A,B=C)).
g__call_goals(A,B:=C,D):-m__body__(call_goals(A,B:=C,D),D=m__body__(A,B is C)).
g__call_goals(A,B is C,D):-m__body__(call_goals(A,B is C,D),D=m__body__(A,B is C)).
g__call_goals(A,B=..C,D):-m__body__(call_goals(A,B=..C,D),D=m__body__(A,B=..C)).
g__call_goals(A,prolog(B),C):-m__body__(call_goals(A,prolog(B),C),C=m__body__(A,B)).
g__call_goals(A,call(B),C):-m__body__(call_goals(A,call(B),C),C=m__body__(A,m__call__(B))).
g__call_goals(A,freeze(B,C),D):-m__body__(call_goals(A,freeze(B,C),D),
		  D=m__body__(A,m__freeze__(A,B,C))).
g__call_goals(A,catch(B,C,D),E):-m__body__(call_goals(A,catch(B,C,D),E),
		  E=m__body__(A,m__catch__(B,C,D))).
g__call_goals(A,abolish(B,C),D):-m__body__(call_goals(A,abolish(B,C),D),
		  D=m__body__(A,m__abolish__(B,C))).
g__call_goals(A,asserta(B),C):-m__body__(call_goals(A,asserta(B),C),C=m__body__(A,m__asserta__(B))).
g__call_goals(A,assertz(B),C):-m__body__(call_goals(A,assertz(B),C),C=m__body__(A,m__assertz__(B))).
g__call_goals(A,B,C):-m__body__(call_goals(A,B,C),g__rename_term(B,D)),!,m__body__(call_goals(A,B,C),C=m__body__(A,D)).
g__rename_term(A,B):-m__body__(rename_term(A,B),A=..[C|D]),!,m__body__(rename_term(A,B),g__atom_concat(g__,C,E)),!,m__body__(rename_term(A,B),B=..[E|D]).
g__preprocess_dcg([],[]).
g__preprocess_dcg([term_data(A,B)|C],[term_data(D,B)|E]):-m__body__(preprocess_dcg([term_data(A,B)|C],[term_data(D,B)|E]),
		  g__preprocess_dcg_term(A,D)),!,m__body__(preprocess_dcg([term_data(A,B)|C],[term_data(D,B)|E]),
		  g__preprocess_dcg(C,E)).
g__preprocess_dcg_term((A-->B|C),D):-( m__guard__(preprocess_dcg_term((A-->B|C),D),E=(A-->B|C)),
  m__guard__(preprocess_dcg_term((A-->B|C),D),g__may_be_stream(B)),
  m__guard__(preprocess_dcg_term((A-->B|C),D),g__may_be_stream(C))
),!,m__body__(preprocess_dcg_term((A-->B|C),D),
		  g__throw(error(invalid_predicate(E)))).
g__preprocess_dcg_term((A-->B|C),(D:-E|F)):-( m__guard__(preprocess_dcg_term((A-->B|C),(D:-E|F)),G=(A-->B|C)),
  m__guard__(preprocess_dcg_term((A-->B|C),(D:-E|F)),
			 g__may_be_stream(B))
),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),
		  g__preprocess_dcg_stream(G,B,H-I,E)),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),A=..[J|K]),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),g__append(K,[H,I],L)),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),D=..[J|L]),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),F=C).
g__preprocess_dcg_term((A-->B|C),(D:-E|F)):-( m__guard__(preprocess_dcg_term((A-->B|C),(D:-E|F)),G=(A-->B|C)),
  m__guard__(preprocess_dcg_term((A-->B|C),(D:-E|F)),
			 g__may_be_stream(C))
),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),
		  g__preprocess_dcg_stream(G,C,H-I,F)),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),A=..[J|K]),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),g__append(K,[H,I],L)),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),D=..[J|L]),!,m__body__(preprocess_dcg_term((A-->B|C),(D:-E|F)),E=B).
g__preprocess_dcg_term((A-->B),(C:-D)):-( m__guard__(preprocess_dcg_term((A-->B),(C:-D)),E=(A-->B)),
  m__guard__(preprocess_dcg_term((A-->B),(C:-D)),g__may_be_stream(B))
),!,m__body__(preprocess_dcg_term((A-->B),(C:-D)),
		  g__preprocess_dcg_stream(E,B,F-G,D)),!,m__body__(preprocess_dcg_term((A-->B),(C:-D)),A=..[H|I]),!,m__body__(preprocess_dcg_term((A-->B),(C:-D)),g__append(I,[F,G],J)),!,m__body__(preprocess_dcg_term((A-->B),(C:-D)),C=..[H|J]).
g__preprocess_dcg_term(A,A).
g__may_be_stream(A):-( m__guard__(may_be_stream(A),g__may_be_stream(A,false,B)),
  m__guard__(may_be_stream(A),B=true)
),!,true.
g__may_be_stream(({A},B),C,D):-m__body__(may_be_stream(({A},B),C,D),D=true).
g__may_be_stream(([],A),B,C):-m__body__(may_be_stream(([],A),B,C),C=true).
g__may_be_stream(([A|B],C),D,E):-m__body__(may_be_stream(([A|B],C),D,E),E=true).
g__may_be_stream((A,B),C,D):-m__body__(may_be_stream((A,B),C,D),g__may_be_stream(B,C,D)).
g__may_be_stream({A},B,C) :- m__body__(may_be_stream({A},B,C),C=true).
g__may_be_stream([],A,B) :- m__body__(may_be_stream([],A,B),B=true).
g__may_be_stream([A|B],C,D) :- m__body__(may_be_stream([A|B],C,D),D=true).
g__may_be_stream(A,B,C) :- m__body__(may_be_stream(A,B,C),C=B).
g__preprocess_dcg_stream(A,(B,C),D-E,F):-m__guard__(preprocess_dcg_stream(A,(B,C),D-E,F),B=[]),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,F),
		  g__preprocess_dcg_stream(A,C,D-E,F)).
g__preprocess_dcg_stream(A,(B,C),D-E,(F,G)):-m__guard__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),B=[_|_]),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),
		  g__extend_list(B,H-I)),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),F=(D=H)),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),
		  g__preprocess_dcg_stream(A,C,I-E,G)).
g__preprocess_dcg_stream(A,(B,C),D-E,(F,G)):-m__guard__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),B={H}),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),F=H),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),
		  g__preprocess_dcg_stream(A,C,D-E,G)).
g__preprocess_dcg_stream(A,(B,C),D-E,(F,G)):-m__guard__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),B=..[H|I]),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),
		  g__append(I,[D,J],K)),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),F=..[H|K]),!,m__body__(preprocess_dcg_stream(A,(B,C),D-E,(F,G)),
		  g__preprocess_dcg_stream(A,C,J-E,G)).
g__preprocess_dcg_stream(A,B,C-D,E):-m__guard__(preprocess_dcg_stream(A,B,C-D,E),B=[]),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),E=(C=D)).
g__preprocess_dcg_stream(A,B,C-D,E):-m__guard__(preprocess_dcg_stream(A,B,C-D,E),B=[_|_]),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),g__extend_list(B,F-D)),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),E=(C=F)).
g__preprocess_dcg_stream(A,B,C-D,E):-m__guard__(preprocess_dcg_stream(A,B,C-D,E),B={F}),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),E=F),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),C=D).
g__preprocess_dcg_stream(A,B,C-D,E):-m__guard__(preprocess_dcg_stream(A,B,C-D,E),B=..[F|G]),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),g__append(G,[C,D],H)),!,m__body__(preprocess_dcg_stream(A,B,C-D,E),E=..[F|H]).
g__preprocess_dcg_stream(A,(B,C),D,E):-m__body__(preprocess_dcg_stream(A,(B,C),D,E),
		  g__throw(error(invalid_predicate(A,B)))).
g__preprocess_dcg_stream(A,B,C,D):-m__body__(preprocess_dcg_stream(A,B,C,D),
		  g__throw(error(invalid_predicate(A,B)))).
g__extend_list([],A-A).
g__extend_list([A|B],C-D):-m__body__(extend_list([A|B],C-D),C=[A|E]),!,m__body__(extend_list([A|B],C-D),g__extend_list(B,E-D)).
